//=============================================================================
// TOModels
//=============================================================================
//
// Tactical Ops
// - http://www.planetunreal.com/tacticalops
//
// Source code rights:
// Copyright (C) 2000/2001 Laurent "SHAG" Delayen
//=============================================================================

class TOModels extends Actor;

/*

- LODSTYLE
A bit field with switches to change the style of building the pre-collapse sequence.
By default, none of these bits are set.
Useful ones right now are 8 and 2 in particular.

1: Value curvature over length.
2: Protect the edges of doublesided polygons - like the CTF flags.
4: Try to respect texture seams more. Use this if there is too much 'stretching' going on.
8: Value length over curvature. Needed for unwelded, multi-element, or otherwise 'open' meshes like the new superhealth.
16: Translucent polygons will be collapsed less early in the LOD sequence. (Broken in the 224 code base.)

*/


#exec TEXTURE IMPORT NAME=arms_sf		FILE=TEXTURES\skins\player\swat_hands.pcx		GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=arms_t		FILE=TEXTURES\skins\player\t_hands.pcx			GROUP="Skins"	LODSET=2 


///////////////////////////////////////
// 3rd person view muzzles!
///////////////////////////////////////

//#exec MESH IMPORT MESH=TO3rdMuzzle ANIVFILE=MODELS\Muzzle\3rdmuzzle_a.3d DATAFILE=MODELS\Muzzle\3rdmuzzle_d.3d X=0 Y=0 Z=0 LODSTYLE=8
//#exec MESH ORIGIN MESH=TO3rdMuzzle X=-140 Y=0 Z=-10
//#exec MESH SEQUENCE MESH=TO3rdMuzzle SEQ=All  STARTFRAME=0  NUMFRAMES=1

//#exec TEXTURE IMPORT NAME=bigmuzzle-1-3rd FILE=Textures\3rdmuzzles\bigmuzzle-1-3rd.bmp
#exec TEXTURE IMPORT NAME=bigmuzzle-2-3rd FILE=Textures\3rdmuzzles\bigmuzzle-2-3rd.pcx 
//#exec TEXTURE IMPORT NAME=bigmuzzle-3-3rd FILE=Textures\3rdmuzzles\bigmuzzle-3-3rd.bmp
#exec TEXTURE IMPORT NAME=bigmuzzle-4-3rd FILE=Textures\3rdmuzzles\bigmuzzle-4-3rd.pcx
//#exec TEXTURE IMPORT NAME=smallmuzzle-1-3rd.bmp FILE=Textures\3rdmuzzles\smallmuzzle-1-3rd.bmp
//#exec TEXTURE IMPORT NAME=smallmuzzle-2-3rd.bmp FILE=Textures\3rdmuzzles\smallmuzzle-2-3rd.bmp
//#exec TEXTURE IMPORT NAME=smallmuzzle-3-3rd.bmp FILE=Textures\3rdmuzzles\smallmuzzle-3-3rd.bmp

//#exec MESHMAP SCALE MESHMAP=TO3rdMuzzle X=0.95 Y=0.80 Z=1.5
//#exec MESHMAP SETTEXTURE MESHMAP=TO3rdMuzzle NUM=1 TEXTURE=bigmuzzle-1-3rd 


// Ak 47 Muzzle
#exec MESH IMPORT MESH=TO3rdMuzzleAk ANIVFILE=MODELS\Muzzle\3rdmuzzle_a.3d DATAFILE=MODELS\Muzzle\3rdmuzzle_d.3d X=0 Y=0 Z=0 LODSTYLE=2
#exec MESH ORIGIN MESH=TO3rdMuzzleAk X=-210 Y=0 Z=-15
#exec MESH SEQUENCE MESH=TO3rdMuzzleAk SEQ=All  STARTFRAME=0  NUMFRAMES=1
// X=Z, Y=X, Z=Y
#exec MESHMAP SCALE MESHMAP=TO3rdMuzzleAk X=0.60 Y=0.45 Z=0.85
#exec MESHMAP SETTEXTURE MESHMAP=TO3rdMuzzleAk NUM=1 TEXTURE=bigmuzzle-2-3rd


// Steyr Aug Muzzle
#exec MESH IMPORT MESH=TO3rdMuzzleSA ANIVFILE=MODELS\Muzzle\3rdmuzzle_a.3d DATAFILE=MODELS\Muzzle\3rdmuzzle_d.3d X=0 Y=0 Z=0 LODSTYLE=2
#exec MESH ORIGIN MESH=TO3rdMuzzleSA X=-280 Y=0 Z=-20
#exec MESH SEQUENCE MESH=TO3rdMuzzleSA SEQ=All  STARTFRAME=0  NUMFRAMES=1
#exec MESHMAP SCALE MESHMAP=TO3rdMuzzleSA X=0.40 Y=0.35 Z=0.65
#exec MESHMAP SETTEXTURE MESHMAP=TO3rdMuzzleSA NUM=1 TEXTURE=bigmuzzle-4-3rd


///////////////////////////////////////
// shells
///////////////////////////////////////

// 9mm
#exec MESH IMPORT MESH=s9mmsc ANIVFILE=MODELS\shells\9mm_a.3d DATAFILE=MODELS\shells\9mm_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=s9mmsc X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=s9mmsc SEQ=All  STARTFRAME=0  NUMFRAMES=1

#exec TEXTURE IMPORT NAME=ShellSkin FILE=Textures\Weapons\shells\shells_template.pcx 

#exec MESHMAP SCALE MESHMAP=s9mmsc X=0.007 Y=0.007 Z=0.014
#exec MESHMAP SETTEXTURE MESHMAP=s9mmsc NUM=1 TEXTURE=ShellSkin 

// .50
#exec MESH IMPORT MESH=s50bmg ANIVFILE=MODELS\shells\50bmg_a.3d DATAFILE=MODELS\shells\50bmg_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=s50bmg X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=s50bmg SEQ=All  STARTFRAME=0  NUMFRAMES=1

#exec MESHMAP SCALE MESHMAP=s50bmg X=0.007 Y=0.007 Z=0.014
#exec MESHMAP SETTEXTURE MESHMAP=s50bmg NUM=1 TEXTURE=ShellSkin 

// 12ga
#exec MESH IMPORT MESH=s12ga ANIVFILE=MODELS\shells\12ga_a.3d DATAFILE=MODELS\shells\12ga_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=s12ga X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=s12ga SEQ=All  STARTFRAME=0  NUMFRAMES=1

#exec MESHMAP SCALE MESHMAP=s12ga X=0.007 Y=0.007 Z=0.014
#exec MESHMAP SETTEXTURE MESHMAP=s12ga NUM=1 TEXTURE=ShellSkin

// 7.62
#exec MESH IMPORT MESH=s762 ANIVFILE=MODELS\shells\762_a.3d DATAFILE=MODELS\shells\762_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=s762 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=s762 SEQ=All  STARTFRAME=0  NUMFRAMES=1

#exec MESHMAP SCALE MESHMAP=s762 X=0.007 Y=0.007 Z=0.014
#exec MESHMAP SETTEXTURE MESHMAP=s762 NUM=1 TEXTURE=ShellSkin

// 5.56
#exec MESH IMPORT MESH=SC556 ANIVFILE=MODELS\shells\556_a.3d DATAFILE=MODELS\shells\556_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN MESH=SC556 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=SC556 SEQ=All  STARTFRAME=0  NUMFRAMES=1

#exec MESHMAP SCALE MESHMAP=SC556 X=0.007 Y=0.007 Z=0.014
#exec MESHMAP SETTEXTURE MESHMAP=SC556 NUM=1 TEXTURE=ShellSkin 


///////////////////////////////////////
// grenade
///////////////////////////////////////

// grenade 1st person model
#exec MESH IMPORT MESH=grenade ANIVFILE=MODELS\grenade\grenade_a.3d DATAFILE=MODELS\grenade\grenade_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=grenade  STRENGTH=0.5
#exec MESH ORIGIN MESH=grenade X=-100 Y=650 Z=0 YAW=192 PITCH=0 ROLL=0

/*
#exec MESH SEQUENCE MESH=grenade SEQ=All           STARTFRAME=0 NUMFRAMES=138
#exec MESH SEQUENCE MESH=grenade SEQ=DOWN					 STARTFRAME=0 NUMFRAMES=13
#exec MESH SEQUENCE MESH=grenade SEQ=SELECT				 STARTFRAME=13 NUMFRAMES=14
#exec MESH SEQUENCE MESH=grenade SEQ=THROW         STARTFRAME=27 NUMFRAMES=33
#exec MESH SEQUENCE MESH=grenade SEQ=THROWS        STARTFRAME=27 NUMFRAMES=27
#exec MESH SEQUENCE MESH=grenade SEQ=THROWM        STARTFRAME=53 NUMFRAMES=1
#exec MESH SEQUENCE MESH=grenade SEQ=THROWE        STARTFRAME=54 NUMFRAMES=6
#exec MESH SEQUENCE MESH=grenade SEQ=PULLPIN       STARTFRAME=60 NUMFRAMES=23
#exec MESH SEQUENCE MESH=grenade SEQ=IDLEP			   STARTFRAME=88 NUMFRAMES=1
#exec MESH SEQUENCE MESH=grenade SEQ=THROWP				 STARTFRAME=89 NUMFRAMES=18
#exec MESH SEQUENCE MESH=grenade SEQ=IDLE1				 STARTFRAME=107 NUMFRAMES=31
#exec MESH SEQUENCE MESH=grenade SEQ=IDLE					 STARTFRAME=107 NUMFRAMES=1
#exec MESH SEQUENCE MESH=grenade SEQ=FIX					 STARTFRAME=107 NUMFRAMES=2

0-16 Begin throwing anim (pull pin, frame 16 right hand invisible)
17-24 Start throw (17 ahdn invis top, frame 24 hand ivis buttom, frame 20 is last frame gren is in hand)
25-31 down
32-41 up
42-52 idle (play very very slow)
53-54 2 framer for idle pos
55-56 2 framer for right hand up and ivis position (before throw)
*/

#exec MESH SEQUENCE MESH=grenade SEQ=All           STARTFRAME=0 NUMFRAMES=57
#exec MESH SEQUENCE MESH=grenade SEQ=THROWS				 STARTFRAME=0 NUMFRAMES=17
#exec MESH SEQUENCE MESH=grenade SEQ=THROWE				 STARTFRAME=17 NUMFRAMES=8
#exec MESH SEQUENCE MESH=grenade SEQ=DOWN          STARTFRAME=25 NUMFRAMES=7
#exec MESH SEQUENCE MESH=grenade SEQ=SELECT        STARTFRAME=32 NUMFRAMES=10 RATE=20
#exec MESH SEQUENCE MESH=grenade SEQ=IDLE1				 STARTFRAME=42 NUMFRAMES=11
#exec MESH SEQUENCE MESH=grenade SEQ=IDLE					 STARTFRAME=53 NUMFRAMES=2
#exec MESH SEQUENCE MESH=grenade SEQ=FIX           STARTFRAME=53 NUMFRAMES=2
#exec MESH SEQUENCE MESH=grenade SEQ=THROWM        STARTFRAME=55 NUMFRAMES=2

#exec MESH NOTIFY MESH=grenade SEQ=THROWE TIME=0.60 FUNCTION=MNthrow

#exec TEXTURE IMPORT NAME=grenhe			FILE=TEXTURES\WEAPONS\grenade\grenade_he.pcx			GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=gren_flash  FILE=TEXTURES\WEAPONS\grenade\grenade_flash.pcx		GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=gren_conc		FILE=TEXTURES\WEAPONS\grenade\grenade_conc.pcx		GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=gren_smoke	FILE=TEXTURES\WEAPONS\grenade\grenade_smoke.pcx		GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=grenade MESH=grenade
#exec MESHMAP SCALE MESHMAP=grenade X=0.05	Y=0.05	Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=grenade NUM=1 TEXTURE=grenhe
#exec MESHMAP SETTEXTURE MESHMAP=grenade NUM=2 TEXTURE=arms_sf


// grenade 3rdPerson
#exec MESH IMPORT MESH=wgrenade ANIVFILE=MODELS\grenade\wgren_a.3d DATAFILE=MODELS\grenade\wgren_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wgrenade  STRENGTH=0.5
#exec MESH ORIGIN MESH=wgrenade X=0 Y=0 Z=0 YAW=64 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=wgrenade MESH=wgrenade
#exec MESHMAP SCALE MESHMAP=wgrenade X=0.02 Y=0.02 Z=0.04

#exec MESHMAP SETTEXTURE MESHMAP=wgrenade NUM=1 TEXTURE=grenhe


///////////////////////////////////////
// knife
///////////////////////////////////////

// knife 1st person model
#exec MESH IMPORT MESH=sknife ANIVFILE=MODELS\knife\knifeopt_a.3d DATAFILE=MODELS\knife\knifeopt_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=sknife  STRENGTH=0.5
#exec MESH ORIGIN MESH=sknife X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0


#exec MESH SEQUENCE MESH=sknife SEQ=All			STARTFRAME=0	NUMFRAMES=133
#exec MESH SEQUENCE MESH=sknife SEQ=DOWN		STARTFRAME=0	NUMFRAMES=6	
#exec MESH SEQUENCE MESH=sknife SEQ=SELECT	STARTFRAME=6	NUMFRAMES=10
#exec MESH SEQUENCE MESH=sknife SEQ=CLEAN		STARTFRAME=16	NUMFRAMES=9	
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE		STARTFRAME=33	NUMFRAMES=2
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE1		STARTFRAME=25	NUMFRAMES=9
#exec MESH SEQUENCE MESH=sknife SEQ=Fix			STARTFRAME=33	NUMFRAMES=2
#exec MESH SEQUENCE MESH=sknife SEQ=SLASH1	STARTFRAME=34 NUMFRAMES=15
#exec MESH SEQUENCE MESH=sknife SEQ=SLASH2	STARTFRAME=49	NUMFRAMES=15
#exec MESH SEQUENCE MESH=sknife SEQ=SWITCH  STARTFRAME=64	NUMFRAMES=14
#exec MESH SEQUENCE MESH=sknife SEQ=SWITCHT STARTFRAME=78	NUMFRAMES=14
#exec MESH SEQUENCE MESH=sknife SEQ=THROW		STARTFRAME=92	NUMFRAMES=13
#exec MESH SEQUENCE MESH=sknife SEQ=DOWNT		STARTFRAME=105 NUMFRAMES=6
#exec MESH SEQUENCE MESH=sknife SEQ=SELECTT STARTFRAME=111 NUMFRAMES=6
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE1T  STARTFRAME=120 NUMFRAMES=9
#exec MESH SEQUENCE MESH=sknife SEQ=FixT	  STARTFRAME=119 NUMFRAMES=2
#exec MESH SEQUENCE MESH=sknife SEQ=IDLET		STARTFRAME=119 NUMFRAMES=2

#exec MESH NOTIFY MESH=sknife SEQ=SLASH1 TIME=0.40 FUNCTION=SlashHit
#exec MESH NOTIFY MESH=sknife SEQ=SLASH2 TIME=0.50 FUNCTION=SlashHit
//#exec MESH NOTIFY MESH=sknife SEQ=STAB	 TIME=0.50 FUNCTION=SlashHit
#exec MESH NOTIFY MESH=sknife SEQ=CLEAN	 TIME=0.40 FUNCTION=fCleanBlade
#exec MESH NOTIFY MESH=sknife SEQ=THROW	 TIME=0.75 FUNCTION=ThrowKnife


/*
animations
S- = Slash anim
T- = Throw anim
(youll understand what i mean there)

0-5 S-down
6-15 S-up
16-24 S-clean
25-33 S-idle
34-48 Slash1
49-63 Slash2
64-77 Switch (slash to throw)
78-91 Switch (throw to slash)
92-104 T-throw
105-110 T-down
---------------------- ( i might have screwed up beyond this)
111-119 T-up
120-128 T-idle
129-130 2framer for slash
131-132 2framer for throw

skins

skin1 knife
skin2 hands

#exec MESH SEQUENCE MESH=sknife SEQ=All			STARTFRAME=0	NUMFRAMES=369
#exec MESH SEQUENCE MESH=sknife SEQ=DOWN		STARTFRAME=0	NUMFRAMES=19
#exec MESH SEQUENCE MESH=sknife SEQ=SELECT	STARTFRAME=19	NUMFRAMES=44
#exec MESH SEQUENCE MESH=sknife SEQ=CLEAN		STARTFRAME=63	NUMFRAMES=35
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE		STARTFRAME=62	NUMFRAMES=1
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE1		STARTFRAME=98	NUMFRAMES=41
#exec MESH SEQUENCE MESH=sknife SEQ=Fix			STARTFRAME=97	NUMFRAMES=2
#exec MESH SEQUENCE MESH=sknife SEQ=SLASH1	STARTFRAME=139  NUMFRAMES=23
#exec MESH SEQUENCE MESH=sknife SEQ=SLASH2	STARTFRAME=162	NUMFRAMES=28
#exec MESH SEQUENCE MESH=sknife SEQ=STAB		STARTFRAME=190	NUMFRAMES=22
#exec MESH SEQUENCE MESH=sknife SEQ=SWITCH  STARTFRAME=212	NUMFRAMES=38
#exec MESH SEQUENCE MESH=sknife SEQ=THROW		STARTFRAME=250	NUMFRAMES=17
#exec MESH SEQUENCE MESH=sknife SEQ=DOWNT		STARTFRAME=267	NUMFRAMES=14
#exec MESH SEQUENCE MESH=sknife SEQ=SELECTT STARTFRAME=281	NUMFRAMES=38
#exec MESH SEQUENCE MESH=sknife SEQ=IDLE1T  STARTFRAME=299	NUMFRAMES=31
#exec MESH SEQUENCE MESH=sknife SEQ=FixT	  STARTFRAME=298	NUMFRAMES=2
#exec MESH SEQUENCE MESH=sknife SEQ=IDLET		STARTFRAME=330	NUMFRAMES=1
#exec MESH SEQUENCE MESH=sknife SEQ=SWITCHT STARTFRAME=331	NUMFRAMES=38
*/



#exec TEXTURE IMPORT NAME=JBlade0 FILE=TEXTURES\WEAPONS\knife\knife_clean.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JBlade1 FILE=TEXTURES\WEAPONS\knife\knife1b.pcx				GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JBlade2 FILE=TEXTURES\WEAPONS\knife\knife2b.pcx				GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=sknife MESH=sknife
#exec MESHMAP SCALE MESHMAP=sknife X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=sknife NUM=1 TEXTURE=JBlade0
#exec MESHMAP SETTEXTURE MESHMAP=sknife NUM=2 TEXTURE=arms_sf


// knife 3rdPerson
#exec MESH IMPORT MESH=wknife ANIVFILE=MODELS\knife\wknife_a.3d DATAFILE=MODELS\knife\wknife_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wknife  STRENGTH=0.5
#exec MESH ORIGIN MESH=wknife X=-20 Y=0 Z=-30 YAW=-64 PITCH=0 ROLL=0

//#exec TEXTURE IMPORT NAME=Jknife1 FILE=TEXTURES\WEAPONS\knife\skin1b.BMP				GROUP="Skins"	LODSET=2 
//exec TEXTURE IMPORT NAME=Jknife2 FILE=TEXTURES\WEAPONS\knife\skin2b.BMP				GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wknife MESH=wknife
#exec MESHMAP SCALE MESHMAP=wknife X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=wknife NUM=1 TEXTURE=JBlade0
//#exec MESHMAP SETTEXTURE MESHMAP=wknife NUM=0 TEXTURE=Jknife2
//#exec MESHMAP SETTEXTURE MESHMAP=wknife NUM=1 TEXTURE=Jknife1


// knife Pickup
#exec MESH IMPORT MESH=pknife ANIVFILE=MODELS\knife\wknife_a.3d DATAFILE=MODELS\knife\wknife_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pknife  STRENGTH=0.5
#exec MESH ORIGIN MESH=pknife X=0 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pknife MESH=pknife
#exec MESHMAP SCALE MESHMAP=pknife X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=pknife NUM=1 TEXTURE=JBlade0
//#exec MESHMAP SETTEXTURE MESHMAP=pknife NUM=0 TEXTURE=Jknife2
//#exec MESHMAP SETTEXTURE MESHMAP=pknife NUM=1 TEXTURE=Jknife1


// knife throwing
#exec MESH IMPORT MESH=tknife ANIVFILE=MODELS\knife\wknife_a.3d DATAFILE=MODELS\knife\wknife_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=tknife  STRENGTH=0.5
#exec MESH ORIGIN MESH=tknife X=-100 Y=0 Z=-30 YAW=64 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=tknife MESH=tknife
#exec MESHMAP SCALE MESHMAP=tknife X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=tknife NUM=1 TEXTURE=JBlade0


///////////////////////////////////////
// C4
///////////////////////////////////////

// 1st person model
#exec MESH IMPORT MESH=C4 ANIVFILE=MODELS\C4\C4_a.3d DATAFILE=MODELS\C4\C4_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=C4  STRENGTH=0.5
#exec MESH ORIGIN MESH=C4 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=C4 SEQ=All				STARTFRAME=0		NUMFRAMES=79
#exec MESH SEQUENCE MESH=C4 SEQ=Down			STARTFRAME=0		NUMFRAMES=11	RATE 10
#exec MESH SEQUENCE MESH=C4 SEQ=SELECT		STARTFRAME=11		NUMFRAMES=10	RATE 15
#exec MESH SEQUENCE MESH=C4 SEQ=IDLE1     STARTFRAME=21		NUMFRAMES=10  RATE 15
#exec MESH SEQUENCE MESH=C4 SEQ=Fire			STARTFRAME=31		NUMFRAMES=45	
#exec MESH SEQUENCE MESH=C4 SEQ=Fix				STARTFRAME=77		NUMFRAMES=2
#exec MESH SEQUENCE MESH=C4 SEQ=IDLE      STARTFRAME=77		NUMFRAMES=2

#exec MESH NOTIFY MESH=C4 SEQ=Fire TIME=0.25 FUNCTION=PlayC4Arming
/*
0-10 down
11-20 up
21-30 longidle
31-76 Act. + Drop
77-78 still idle
*/

#exec TEXTURE IMPORT NAME=JC41 FILE=TEXTURES\WEAPONS\C4\c4_worldnew.pcx			GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=C4 MESH=C4
#exec MESHMAP SCALE MESHMAP=C4 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=C4 NUM=1 TEXTURE=JC41
#exec MESHMAP SETTEXTURE MESHMAP=C4 NUM=2 TEXTURE=arms_sf

// C4 3rdPerson
#exec MESH IMPORT MESH=wC4 ANIVFILE=MODELS\C4\c4worldold_a.3d DATAFILE=MODELS\C4\c4worldold_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wC4  STRENGTH=0.5
#exec MESH ORIGIN MESH=wC4 X=0 Y=0 Z=0 YAW=-64 PITCH=0 ROLL=0

//#exec TEXTURE IMPORT NAME=wJC41 FILE=TEXTURES\WEAPONS\C4\C4_world.bmp GROUP="Skins"	LODSET=2 MIPS=OFF

#exec MESHMAP NEW   MESHMAP=wC4 MESH=wC4
#exec MESHMAP SCALE MESHMAP=wC4 X=0.03 Y=0.03 Z=0.06

#exec MESHMAP SETTEXTURE MESHMAP=wC4 NUM=1 TEXTURE=JC41


// C4 Pickup
#exec MESH IMPORT MESH=pC4 ANIVFILE=MODELS\C4\c4worldold_a.3d DATAFILE=MODELS\C4\c4worldold_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pC4  STRENGTH=0.5
#exec MESH ORIGIN MESH=pC4 X=-300 Y=0 Z=0 YAW=0 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=pC4 MESH=pC4
#exec MESHMAP SCALE MESHMAP=pC4 X=0.06 Y=0.06 Z=0.12

#exec MESHMAP SETTEXTURE MESHMAP=pC4 NUM=1 TEXTURE=JC41


// C4 Flag
#exec MESH IMPORT MESH=flgC4 ANIVFILE=MODELS\C4\c4worldold_a.3d DATAFILE=MODELS\C4\c4worldold_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=flgC4  STRENGTH=0.5
#exec MESH ORIGIN MESH=pC4 X=0 Y=0 Z=0 YAW=0 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=flgC4 MESH=flgC4
#exec MESHMAP SCALE MESHMAP=flgC4 X=0.06 Y=0.06 Z=0.12

#exec MESHMAP SETTEXTURE MESHMAP=flgC4 NUM=1 TEXTURE=JC41

// C4 explosive
#exec OBJ LOAD FILE=Textures\TOTexts.utx  PACKAGE=TOModels.TOTexts

#exec MESH IMPORT MESH=eC4 ANIVFILE=MODELS\C4\c4world_a.3d DATAFILE=MODELS\C4\c4world_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=eC4  STRENGTH=0.5
#exec MESH ORIGIN MESH=eC4 X=-300 Y=0 Z=0 YAW=0 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=eC4 MESH=eC4
#exec MESHMAP SCALE MESHMAP=eC4 X=0.06 Y=0.06 Z=0.12

#exec MESHMAP SETTEXTURE MESHMAP=eC4 NUM=1 TEXTURE=JC41
#exec MESHMAP SETTEXTURE MESHMAP=eC4 NUM=2 TEXTURE=TOModels.TOTexts.C4Display


///////////////////////////////////////
// Glock 
///////////////////////////////////////

// Glock 1st person model

#exec MESH IMPORT MESH=Glock ANIVFILE=MODELS\Glock\Glock211_a.3d DATAFILE=MODELS\Glock\Glock211_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=Glock  STRENGTH=0.5
#exec MESH ORIGIN MESH=Glock X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=Glock SEQ=All            STARTFRAME=0  NUMFRAMES=78
#exec MESH SEQUENCE MESH=Glock SEQ=DOWN           STARTFRAME=0	NUMFRAMES=6		RATE=18
#exec MESH SEQUENCE MESH=Glock SEQ=SELECT         STARTFRAME=6	NUMFRAMES=13	RATE=10
#exec MESH SEQUENCE MESH=Glock SEQ=FIRE           STARTFRAME=19 NUMFRAMES=8
#exec MESH SEQUENCE MESH=Glock SEQ=FIRE1          STARTFRAME=27 NUMFRAMES=7
#exec MESH SEQUENCE MESH=Glock SEQ=FIRELAST       STARTFRAME=34 NUMFRAMES=6
#exec MESH SEQUENCE MESH=Glock SEQ=RELOAD         STARTFRAME=40 NUMFRAMES=36
#exec MESH SEQUENCE MESH=Glock SEQ=IDLE           STARTFRAME=18  NUMFRAMES=1	
#exec MESH SEQUENCE MESH=Glock SEQ=FIX						STARTFRAME=18  NUMFRAMES=1	
#exec MESH SEQUENCE MESH=Glock SEQ=FIXLAST				STARTFRAME=39  NUMFRAMES=1

#exec MESH NOTIFY MESH=Glock SEQ=RELOAD TIME=0.15 FUNCTION=PlayClipOut
#exec MESH NOTIFY MESH=Glock SEQ=RELOAD TIME=0.50 FUNCTION=PlayClipIn
#exec MESH NOTIFY MESH=Glock SEQ=RELOAD TIME=0.70 FUNCTION=PlayClipReload
#exec MESH NOTIFY MESH=Glock SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=Glock SEQ=Fire1	TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=Glock SEQ=FireLast	TIME=0.10 FUNCTION=AnimFire
/*
#exec MESH IMPORT MESH=Glock ANIVFILE=MODELS\Glock\Glock21_a.3d DATAFILE=MODELS\Glock\Glock21_d.3d X=0 Y=0 Z=0 LODSTYLE=8
#exec MESH LODPARAMS MESH=Glock  STRENGTH=0.5
#exec MESH ORIGIN MESH=Glock X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=Glock SEQ=All            STARTFRAME=0  NUMFRAMES=91
#exec MESH SEQUENCE MESH=Glock SEQ=DOWN           STARTFRAME=0	NUMFRAMES=8	
#exec MESH SEQUENCE MESH=Glock SEQ=SELECT         STARTFRAME=9	NUMFRAMES=28
#exec MESH SEQUENCE MESH=Glock SEQ=FIRE           STARTFRAME=37 NUMFRAMES=8
#exec MESH SEQUENCE MESH=Glock SEQ=FIRE1          STARTFRAME=45 NUMFRAMES=7
#exec MESH SEQUENCE MESH=Glock SEQ=FIRELAST       STARTFRAME=52 NUMFRAMES=6
#exec MESH SEQUENCE MESH=Glock SEQ=RELOAD         STARTFRAME=58 NUMFRAMES=31
#exec MESH SEQUENCE MESH=Glock SEQ=IDLE           STARTFRAME=91  NUMFRAMES=2	
#exec MESH SEQUENCE MESH=Glock SEQ=FIX						STARTFRAME=91  NUMFRAMES=2	
*/
/*
0-8 down
9-36 select
37-44 shoot1
45-51 shoot2
52-57 shootlast
58-88 reload
89-90 2frame DONT USE
91-92 2frame use
*/

#exec TEXTURE IMPORT NAME=JGlock1 FILE=TEXTURES\WEAPONS\Glock\magazine.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JGlock2 FILE=TEXTURES\WEAPONS\Glock\main.pcx			GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=Glock MESH=Glock
#exec MESHMAP SCALE MESHMAP=Glock X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=Glock NUM=1 TEXTURE=JGlock1
#exec MESHMAP SETTEXTURE MESHMAP=Glock NUM=2 TEXTURE=JGlock2
#exec MESHMAP SETTEXTURE MESHMAP=Glock NUM=3 TEXTURE=arms_sf


// Glock 3rdPerson
#exec MESH IMPORT MESH=wGlock ANIVFILE=MODELS\Glock\wGlock_a.3d DATAFILE=MODELS\Glock\wGlock_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wGlock  STRENGTH=0.5
#exec MESH ORIGIN MESH=wGlock X=0 Y=400 Z=-100 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wGlock1 FILE=TEXTURES\WEAPONS\Glock\w_glk.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wGlock MESH=wGlock
#exec MESHMAP SCALE MESHMAP=wGlock X=0.010 Y=0.010 Z=0.020

#exec MESHMAP SETTEXTURE MESHMAP=wGlock NUM=1 TEXTURE=wGlock1


// Glock Pickup
#exec MESH IMPORT MESH=pGlock ANIVFILE=MODELS\Glock\wGlock_a.3d DATAFILE=MODELS\Glock\wGlock_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pGlock  STRENGTH=0.5
#exec MESH ORIGIN MESH=pGlock X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pGlock MESH=pGlock
#exec MESHMAP SCALE MESHMAP=pGlock X=0.015 Y=0.015 Z=0.030

#exec MESHMAP SETTEXTURE MESHMAP=pGlock NUM=1 TEXTURE=wGlock1


///////////////////////////////////////
// deagle 
///////////////////////////////////////

// deagle 1st person model
#exec MESH IMPORT			MESH=deagle ANIVFILE=MODELS\deagle\deagle_a.3d DATAFILE=MODELS\deagle\deagle_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=deagle STRENGTH=0.5
#exec MESH ORIGIN			MESH=deagle X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

/*
0-4 fire
5-9 firelast
10-18 down
19-27 up
28-40 idle
41-76 reload
77-78 2framer

#exec MESH SEQUENCE MESH=deagle SEQ=All           STARTFRAME=0		NUMFRAMES=79	
#exec MESH SEQUENCE MESH=deagle SEQ=FIRE          STARTFRAME=0		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=deagle SEQ=FIRELAST      STARTFRAME=5		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=deagle SEQ=DOWN          STARTFRAME=10		NUMFRAMES=9		RATE=10
#exec MESH SEQUENCE MESH=deagle SEQ=SELECT        STARTFRAME=19		NUMFRAMES=10	RATE=10
#exec MESH SEQUENCE MESH=deagle SEQ=IDLE1         STARTFRAME=29		NUMFRAMES=12	
#exec MESH SEQUENCE MESH=deagle SEQ=RELOAD        STARTFRAME=41		NUMFRAMES=36
#exec MESH SEQUENCE MESH=deagle SEQ=IDLE          STARTFRAME=77		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=deagle SEQ=FIX						STARTFRAME=77		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=deagle SEQ=FIXLAST				STARTFRAME=9		NUMFRAMES=1	
*/

#exec MESH SEQUENCE MESH=deagle SEQ=All           STARTFRAME=0		NUMFRAMES=79
#exec MESH SEQUENCE MESH=deagle SEQ=FIRE          STARTFRAME=0		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=deagle SEQ=FIRELAST      STARTFRAME=5		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=deagle SEQ=DOWN          STARTFRAME=10		NUMFRAMES=9		RATE=15
#exec MESH SEQUENCE MESH=deagle SEQ=SELECT        STARTFRAME=19		NUMFRAMES=9		RATE=15
#exec MESH SEQUENCE MESH=deagle SEQ=IDLE1         STARTFRAME=28		NUMFRAMES=13	
#exec MESH SEQUENCE MESH=deagle SEQ=RELOAD        STARTFRAME=41		NUMFRAMES=35
#exec MESH SEQUENCE MESH=deagle SEQ=IDLE          STARTFRAME=27		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=deagle SEQ=FIX						STARTFRAME=27		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=deagle SEQ=FIXLAST				STARTFRAME=9		NUMFRAMES=1	

#exec MESH NOTIFY MESH=deagle SEQ=RELOAD TIME=0.20 FUNCTION=PlayClipOut
#exec MESH NOTIFY MESH=deagle SEQ=RELOAD TIME=0.60 FUNCTION=PlayClipIn
#exec MESH NOTIFY MESH=deagle SEQ=RELOAD TIME=0.80 FUNCTION=PlayClipReload
#exec MESH NOTIFY MESH=deagle SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=deagle SEQ=FireLast	TIME=0.10 FUNCTION=AnimFire


#exec TEXTURE IMPORT NAME=Jdeagle1 FILE=TEXTURES\WEAPONS\deagle\tode1.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jdeagle2 FILE=TEXTURES\WEAPONS\deagle\tode2.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=deagle MESH=deagle
#exec MESHMAP SCALE MESHMAP=deagle X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=deagle NUM=1 TEXTURE=Jdeagle1
#exec MESHMAP SETTEXTURE MESHMAP=deagle NUM=2 TEXTURE=Jdeagle2
#exec MESHMAP SETTEXTURE MESHMAP=deagle NUM=3 TEXTURE=arms_sf

// deagle 3rdPerson
#exec MESH IMPORT MESH=wdeagle ANIVFILE=MODELS\DEAGLE\wde_a.3d DATAFILE=MODELS\DEAGLE\wde_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wdeagle  STRENGTH=0.5
#exec MESH ORIGIN MESH=wdeagle X=0 Y=500 Z=-100 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wdeagle1 FILE=TEXTURES\WEAPONS\DEAGLE\de_world.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wdeagle MESH=wdeagle
#exec MESHMAP SCALE MESHMAP=wdeagle X=0.009000 Y=0.009000 Z=0.018

#exec MESHMAP SETTEXTURE MESHMAP=wdeagle NUM=1 TEXTURE=wdeagle1


// deagle Pickup
#exec MESH IMPORT MESH=pdeagle ANIVFILE=MODELS\DEAGLE\wde_a.3d DATAFILE=MODELS\DEAGLE\wde_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pdeagle  STRENGTH=0.5
#exec MESH ORIGIN MESH=pdeagle X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pdeagle MESH=pdeagle
#exec MESHMAP SCALE MESHMAP=pdeagle X=0.013 Y=0.013 Z=0.026

#exec MESHMAP SETTEXTURE MESHMAP=pdeagle NUM=1 TEXTURE=wdeagle1



///////////////////////////////////////
// Beretta
///////////////////////////////////////

// Beretta 1st person model
/*
#exec MESH IMPORT			MESH=Berreta ANIVFILE=MODELS\Berreta\Beretta215_a.3d DATAFILE=MODELS\Berreta\Beretta215_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN			MESH=Berreta X=0 Y=0 Z=0 YAW=191 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=Berreta SEQ=All          STARTFRAME=0		NUMFRAMES=77	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIRE         STARTFRAME=0		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIRELAST     STARTFRAME=5		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=Berreta SEQ=DOWN					STARTFRAME=10		NUMFRAMES=9		RATE=20
#exec MESH SEQUENCE MESH=Berreta SEQ=SELECT       STARTFRAME=19		NUMFRAMES=8		RATE=15
#exec MESH SEQUENCE MESH=Berreta SEQ=IDLE1        STARTFRAME=27		NUMFRAMES=13
#exec MESH SEQUENCE MESH=Berreta SEQ=RELOAD       STARTFRAME=40		NUMFRAMES=36
#exec MESH SEQUENCE MESH=Berreta SEQ=FIXLAST			STARTFRAME=9		NUMFRAMES=1	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIX					STARTFRAME=76		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=Berreta SEQ=IDLE         STARTFRAME=76		NUMFRAMES=2	


#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.20 FUNCTION=PlayClipOut
#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.60 FUNCTION=PlayClipIn
#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.80 FUNCTION=PlayClipReload
#exec MESH NOTIFY MESH=Berreta SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=Berreta SEQ=FireLast	TIME=0.10 FUNCTION=AnimFire

#exec TEXTURE IMPORT NAME=JBerreta1 FILE=TEXTURES\WEAPONS\Beretta215\B1game.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JBerreta2 FILE=TEXTURES\WEAPONS\Beretta215\BbaseGame.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=Berreta MESH=Berreta
#exec MESHMAP SCALE MESHMAP=Berreta X=0.05 Y=0.05 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=1 TEXTURE=JBerreta1
#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=2 TEXTURE=JBerreta2
#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=3 TEXTURE=arms_sf
*/
/*
0-4 fire
5-9 firelast
10-18 down
19-26 up
27-39 idle
40-75 reload
76-77 2framer
*/

#exec MESH IMPORT			MESH=Berreta ANIVFILE=MODELS\Berreta\Berreta_a.3d DATAFILE=MODELS\Berreta\Berreta_d.3d X=0 Y=0 Z=0
#exec MESH ORIGIN			MESH=Berreta X=0 Y=0 Z=0 YAW=191 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=Berreta SEQ=All          STARTFRAME=0		NUMFRAMES=82	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIRE         STARTFRAME=0		NUMFRAMES=6	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIRELAST     STARTFRAME=6		NUMFRAMES=4	
#exec MESH SEQUENCE MESH=Berreta SEQ=DOWN					STARTFRAME=10		NUMFRAMES=11		RATE=20
#exec MESH SEQUENCE MESH=Berreta SEQ=SELECT       STARTFRAME=21		NUMFRAMES=10		RATE=15
#exec MESH SEQUENCE MESH=Berreta SEQ=IDLE         STARTFRAME=80		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=Berreta SEQ=IDLE1        STARTFRAME=31		NUMFRAMES=11	
#exec MESH SEQUENCE MESH=Berreta SEQ=RELOAD       STARTFRAME=42		NUMFRAMES=36
#exec MESH SEQUENCE MESH=Berreta SEQ=FIXLAST			STARTFRAME=78		NUMFRAMES=2	
#exec MESH SEQUENCE MESH=Berreta SEQ=FIX					STARTFRAME=80		NUMFRAMES=2	

#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.20 FUNCTION=PlayClipOut
#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.60 FUNCTION=PlayClipIn
#exec MESH NOTIFY MESH=Berreta SEQ=RELOAD TIME=0.80 FUNCTION=PlayClipReload
#exec MESH NOTIFY MESH=Berreta SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=Berreta SEQ=FireLast	TIME=0.10 FUNCTION=AnimFire

#exec TEXTURE IMPORT NAME=JBerreta1 FILE=TEXTURES\WEAPONS\Berreta\b1.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JBerreta2 FILE=TEXTURES\WEAPONS\Berreta\bbase.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=Berreta MESH=Berreta
#exec MESHMAP SCALE MESHMAP=Berreta X=0.05 Y=0.05 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=1 TEXTURE=JBerreta1
#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=2 TEXTURE=JBerreta2
#exec MESHMAP SETTEXTURE MESHMAP=Berreta NUM=3 TEXTURE=arms_sf

/*
0-5 fire
6-9 firelast
10-20 down
21-30 up
31-41 idle
42-77 reload
78-79 2framer

skin1 b1
skin2 bbase
skin3 hands
*/




// Beretta 3rdPerson
#exec MESH IMPORT MESH=wberetta ANIVFILE=MODELS\Berreta\berettaw_a.3d DATAFILE=MODELS\Berreta\berettaw_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wberetta  STRENGTH=0.5
#exec MESH ORIGIN MESH=wberetta X=500 Y=-100 Z=0 YAW=-64 PITCH=-64 ROLL=0

#exec TEXTURE IMPORT NAME=wberetta1 FILE=TEXTURES\WEAPONS\Berreta\berettaworld.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wberetta MESH=wberetta
#exec MESHMAP SCALE MESHMAP=wberetta X=0.009 Y=0.009 Z=0.018

#exec MESHMAP SETTEXTURE MESHMAP=wberetta NUM=1 TEXTURE=wberetta1


// Beretta Pickup
#exec MESH IMPORT MESH=pberetta ANIVFILE=MODELS\Berreta\berettaw_a.3d DATAFILE=MODELS\Berreta\berettaw_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pberetta  STRENGTH=0.5
#exec MESH ORIGIN MESH=pberetta X=400 Y=0 Z=0 YAW=-64 PITCH=0 ROLL=0

#exec MESHMAP NEW   MESHMAP=pberetta MESH=pberetta
#exec MESHMAP SCALE MESHMAP=pberetta X=0.013 Y=0.013 Z=0.026

#exec MESHMAP SETTEXTURE MESHMAP=pberetta NUM=1 TEXTURE=wberetta1



///////////////////////////////////////
// MossBerg Shotgun
///////////////////////////////////////

#exec MESH IMPORT			MESH=mossberg	ANIVFILE=MODELS\MossBerg\mossberg_a.3d DATAFILE=MODELS\MossBerg\mossberg_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=mossberg  STRENGTH=0.5
#exec MESH ORIGIN			MESH=mossberg	X=0 Y=0 Z=0 YAW=192

#exec MESH SEQUENCE MESH=mossberg SEQ=All					STARTFRAME=0		NUMFRAMES=72
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOAD			STARTFRAME=0		NUMFRAMES=27	RATE 6  // Reload, no shell in chamber
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOAD1			STARTFRAME=27		NUMFRAMES=5		RATE 9	 // Reload, 1 shell in chamber
#exec MESH SEQUENCE MESH=mossberg SEQ=INSERTSHELL	STARTFRAME=32		NUMFRAMES=10	RATE 7
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOADEND		STARTFRAME=42		NUMFRAMES=5		RATE 6
#exec MESH SEQUENCE MESH=mossberg SEQ=FIRE				STARTFRAME=47		NUMFRAMES=10	RATE 2
#exec MESH SEQUENCE MESH=mossberg SEQ=DOWN				STARTFRAME=57		NUMFRAMES=7		RATE 8
#exec MESH SEQUENCE MESH=mossberg SEQ=SELECT			STARTFRAME=64		NUMFRAMES=5		RATE 7
#exec MESH SEQUENCE MESH=mossberg SEQ=IDLE				STARTFRAME=69		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mossberg SEQ=IDLE1				STARTFRAME=69		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mossberg SEQ=FIX					STARTFRAME=69		NUMFRAMES=2

#exec MESH NOTIFY MESH=mossberg SEQ=RELOAD TIME=0.07 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=mossberg SEQ=RELOAD TIME=0.47 FUNCTION=PlayInsertShellSound
#exec MESH NOTIFY MESH=mossberg SEQ=RELOAD TIME=0.67 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=mossberg SEQ=FIRE TIME=0.67 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=mossberg SEQ=FIRE TIME=0.72 FUNCTION=EjectShell
#exec MESH NOTIFY MESH=mossberg SEQ=Fire		TIME=0.10 FUNCTION=AnimFire

/*

<warflyr> mossberg is: skin1:unt-1, skin2:unt-2, skin3:arms, skin4:shells
<warflyr> my skins for the mossberg are unt-1.bmp, unt-2.bmp
<warflyr> unt-1.bmp has the pump on it

0-26 startempty
27-31 start2
32-41 insert shell
42-46 reload done
47-56 fire1
57-63 down
64-68 up
69-71 2frame

	#exec MESH SEQUENCE MESH=mossberg SEQ=All					STARTFRAME=0		NUMFRAMES=212
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOAD			STARTFRAME=0		NUMFRAMES=63  // Reload, no shell in chamber
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOAD1			STARTFRAME=63		NUMFRAMES=9  // Reload, 1 shell in chamber
#exec MESH SEQUENCE MESH=mossberg SEQ=INSERTSHELL	STARTFRAME=72		NUMFRAMES=24
#exec MESH SEQUENCE MESH=mossberg SEQ=RELOADEND		STARTFRAME=96		NUMFRAMES=12
#exec MESH SEQUENCE MESH=mossberg SEQ=FIRE				STARTFRAME=108	NUMFRAMES=31	RATE=15
#exec MESH SEQUENCE MESH=mossberg SEQ=FIX				STARTFRAME=108	NUMFRAMES=2
#exec MESH SEQUENCE MESH=mossberg SEQ=FIRE2				STARTFRAME=139	NUMFRAMES=30	RATE=15
#exec MESH SEQUENCE MESH=mossberg SEQ=FIRENOPUMP	STARTFRAME=169	NUMFRAMES=11	RATE=15
#exec MESH SEQUENCE MESH=mossberg SEQ=DOWN				STARTFRAME=180	NUMFRAMES=12
#exec MESH SEQUENCE MESH=mossberg SEQ=SELECT			STARTFRAME=192	NUMFRAMES=9
#exec MESH SEQUENCE MESH=mossberg SEQ=IDLE				STARTFRAME=201	NUMFRAMES=1
#exec MESH SEQUENCE MESH=mossberg SEQ=IDLE1				STARTFRAME=201	NUMFRAMES=11

*/



#exec TEXTURE IMPORT NAME=Jmoss_01 FILE=Textures\Weapons\MossBerg\moss-1.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jmoss_02 FILE=Textures\Weapons\MossBerg\moss-2.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=shells FILE=Textures\Weapons\MossBerg\shells.pcx	 GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=mossberg MESH=mossberg
#exec MESHMAP SCALE MESHMAP=mossberg X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=mossberg NUM=1 TEXTURE=Jmoss_01
#exec MESHMAP SETTEXTURE MESHMAP=mossberg NUM=2 TEXTURE=Jmoss_02
#exec MESHMAP SETTEXTURE MESHMAP=mossberg NUM=3 TEXTURE=arms_sf
#exec MESHMAP SETTEXTURE MESHMAP=mossberg NUM=4 TEXTURE=shells

// MossBerg 3rdPerson
#exec MESH IMPORT MESH=wmossberg ANIVFILE=MODELS\mossberg\wmoss_a.3d DATAFILE=MODELS\mossberg\wmoss_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wmossberg  STRENGTH=0.5
#exec MESH ORIGIN MESH=wmossberg X=0 Y=50 Z=0 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=Jmoss1 FILE=TEXTURES\WEAPONS\mossberg\w_moss1.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wmossberg MESH=wmossberg
#exec MESHMAP SCALE MESHMAP=wmossberg X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=wmossberg NUM=1 TEXTURE=Jmoss1


// MossBerg Pickup
#exec MESH IMPORT MESH=pmossberg ANIVFILE=MODELS\mossberg\wmoss_a.3d DATAFILE=MODELS\mossberg\wmoss_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pmossberg  STRENGTH=0.5
#exec MESH ORIGIN MESH=pmossberg X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pmossberg MESH=pmossberg
#exec MESHMAP SCALE MESHMAP=pmossberg X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=pmossberg NUM=1 TEXTURE=Jmoss1



///////////////////////////////////////
// M3 Shotgun
///////////////////////////////////////

#exec MESH IMPORT			MESH=m3	ANIVFILE=MODELS\M3\m3_a.3d DATAFILE=MODELS\M3\m3_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=m3  STRENGTH=0.5
#exec MESH ORIGIN			MESH=m3	X=0 Y=0 Z=0 YAW=192

#exec MESH SEQUENCE MESH=m3 SEQ=All					STARTFRAME=0		NUMFRAMES=73
#exec MESH SEQUENCE MESH=m3 SEQ=RELOAD			STARTFRAME=0		NUMFRAMES=25	RATE 12		// Reload, no shell in chamber
#exec MESH SEQUENCE MESH=m3 SEQ=RELOAD1			STARTFRAME=25		NUMFRAMES=4		RATE 15		// Reload, 1 shell in chamber
#exec MESH SEQUENCE MESH=m3 SEQ=INSERTSHELL	STARTFRAME=29		NUMFRAMES=10	RATE 12
#exec MESH SEQUENCE MESH=m3 SEQ=RELOADEND		STARTFRAME=39		NUMFRAMES=4		RATE 10
#exec MESH SEQUENCE MESH=m3 SEQ=FIRE				STARTFRAME=43		NUMFRAMES=12	RATE 8
#exec MESH SEQUENCE MESH=m3 SEQ=FIRENOPUMP	STARTFRAME=55		NUMFRAMES=6  	RATE 10
#exec MESH SEQUENCE MESH=m3 SEQ=DOWN				STARTFRAME=61		NUMFRAMES=4		RATE 12
#exec MESH SEQUENCE MESH=m3 SEQ=SELECT			STARTFRAME=65		NUMFRAMES=6		RATE 20
#exec MESH SEQUENCE MESH=m3 SEQ=IDLE				STARTFRAME=71		NUMFRAMES=2
#exec MESH SEQUENCE MESH=m3 SEQ=IDLE1				STARTFRAME=71		NUMFRAMES=2
#exec MESH SEQUENCE MESH=m3 SEQ=FIX					STARTFRAME=71		NUMFRAMES=2

#exec MESH NOTIFY MESH=m3 SEQ=RELOAD TIME=0.07 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=m3 SEQ=RELOAD TIME=0.47 FUNCTION=PlayInsertShellSound
#exec MESH NOTIFY MESH=m3 SEQ=RELOAD TIME=0.67 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=m3 SEQ=FIRE TIME=0.67 FUNCTION=PlayPump
#exec MESH NOTIFY MESH=m3 SEQ=FIRE TIME=0.72 FUNCTION=EjectShell
#exec MESH NOTIFY MESH=m3 SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
/*
0-24 startempty
25-28 start2
29-38 insert shell
39-42 reload done
43-54 shoot1
55-60 shootlast
61-64 down
65-70 up
71-72 2frame

#exec MESH SEQUENCE MESH=m3 SEQ=All					STARTFRAME=0		NUMFRAMES=187
#exec MESH SEQUENCE MESH=m3 SEQ=RELOAD			STARTFRAME=0		NUMFRAMES=63  // Reload, no shell in chamber
#exec MESH SEQUENCE MESH=m3 SEQ=RELOAD1			STARTFRAME=63		NUMFRAMES=8  // Reload, 1 shell in chamber
#exec MESH SEQUENCE MESH=m3 SEQ=INSERTSHELL	STARTFRAME=71		NUMFRAMES=25
#exec MESH SEQUENCE MESH=m3 SEQ=RELOADEND		STARTFRAME=96		NUMFRAMES=12
#exec MESH SEQUENCE MESH=m3 SEQ=FIRE				STARTFRAME=108	NUMFRAMES=20	RATE=15
#exec MESH SEQUENCE MESH=m3 SEQ=FIX					STARTFRAME=108	NUMFRAMES=2
#exec MESH SEQUENCE MESH=m3 SEQ=FIRE2				STARTFRAME=128	NUMFRAMES=20	RATE=15
#exec MESH SEQUENCE MESH=m3 SEQ=FIRENOPUMP	STARTFRAME=148	NUMFRAMES=9  	RATE=15
#exec MESH SEQUENCE MESH=m3 SEQ=DOWN				STARTFRAME=157	NUMFRAMES=10
#exec MESH SEQUENCE MESH=m3 SEQ=SELECT			STARTFRAME=167	NUMFRAMES=7
#exec MESH SEQUENCE MESH=m3 SEQ=IDLE				STARTFRAME=174	NUMFRAMES=1
#exec MESH SEQUENCE MESH=m3 SEQ=IDLE1				STARTFRAME=174	NUMFRAMES=13
*/


#exec TEXTURE IMPORT NAME=Jm3_01 FILE=Textures\Weapons\M3\main.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jm3_02 FILE=Textures\Weapons\M3\pump.pcx GROUP="Skins"	LODSET=2 
//#exec TEXTURE IMPORT NAME=Jm3_08 FILE=Textures\Weapons\M3\shells.BMP GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=m3 MESH=m3
#exec MESHMAP SCALE MESHMAP=m3 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=m3 NUM=1 TEXTURE=Jm3_01
#exec MESHMAP SETTEXTURE MESHMAP=m3 NUM=2 TEXTURE=Jm3_02
#exec MESHMAP SETTEXTURE MESHMAP=m3 NUM=3 TEXTURE=arms_sf
#exec MESHMAP SETTEXTURE MESHMAP=m3 NUM=4 TEXTURE=shells

// M3 3rdPerson
#exec MESH IMPORT MESH=wm3 ANIVFILE=MODELS\M3\m3world_a.3d DATAFILE=MODELS\M3\m3world_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wm3  STRENGTH=0.5
#exec MESH ORIGIN MESH=wm3 X=0 Y=-200 Z=-35 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=Jwm3 FILE=TEXTURES\WEAPONS\M3\world.pcx GROUP="Skins"	LODSET=2 MIPS=OFF

#exec MESHMAP NEW   MESHMAP=wm3 MESH=wm3
#exec MESHMAP SCALE MESHMAP=wm3 X=0.04 Y=0.03 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=wm3 NUM=1 TEXTURE=Jwm3


// M3 Pickup
#exec MESH IMPORT MESH=pm3 ANIVFILE=MODELS\M3\m3world_a.3d DATAFILE=MODELS\M3\m3world_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pm3  STRENGTH=0.5
#exec MESH ORIGIN MESH=pm3 X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pm3 MESH=pm3
#exec MESHMAP SCALE MESHMAP=pm3 X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=pm3 NUM=1 TEXTURE=Jwm3



///////////////////////////////////////
// FAMAS
///////////////////////////////////////


// FAMAS 1st person model
#exec MESH IMPORT MESH=FAMAS ANIVFILE=MODELS\FAMAS\famas_a.3d DATAFILE=MODELS\FAMAS\famas_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=FAMAS  STRENGTH=0.5
#exec MESH ORIGIN MESH=FAMAS X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0


#exec MESH SEQUENCE MESH=FAMAS SEQ=All				STARTFRAME=0		NUMFRAMES=72
#exec MESH SEQUENCE MESH=FAMAS SEQ=FIRE       STARTFRAME=0		NUMFRAMES=5	
#exec MESH SEQUENCE MESH=FAMAS SEQ=DOWN       STARTFRAME=5		NUMFRAMES=9		RATE 15
#exec MESH SEQUENCE MESH=FAMAS SEQ=SELECT     STARTFRAME=14		NUMFRAMES=9		RATE 15
#exec MESH SEQUENCE MESH=FAMAS SEQ=IDLE1      STARTFRAME=23		NUMFRAMES=11	
#exec MESH SEQUENCE MESH=FAMAS SEQ=RELOAD     STARTFRAME=34		NUMFRAMES=37  
#exec MESH SEQUENCE MESH=FAMAS SEQ=FIX				STARTFRAME=70		NUMFRAMES=2
#exec MESH SEQUENCE MESH=FAMAS SEQ=IDLE       STARTFRAME=70		NUMFRAMES=2

#exec MESH NOTIFY MESH=FAMAS SEQ=RELOAD TIME=0.23 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=FAMAS SEQ=RELOAD TIME=0.55 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=FAMAS SEQ=RELOAD TIME=0.83 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=FAMAS SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
/*
anims
0-4 fire
5-13 down
14-22 up
23-33 idle
34-70 reload
71-72 2frame

skin1 fbody1
skin2 fbody2
skin3 sightsf
skin4 railfamas
skin5 hands

text
skin1 fbody1
skin2 fbody2
skin3 sightsf
skin4 railfamas
skin5 hands
*/

#exec TEXTURE IMPORT NAME=Jfamas1 FILE=TEXTURES\WEAPONS\FAMAS\fbody1.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jfamas2 FILE=TEXTURES\WEAPONS\FAMAS\fbody2.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jfamas3 FILE=TEXTURES\WEAPONS\FAMAS\sightsfc.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jfamas4 FILE=TEXTURES\WEAPONS\FAMAS\railfamas.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=FAMAS MESH=FAMAS
#exec MESHMAP SCALE MESHMAP=FAMAS X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=FAMAS NUM=1 TEXTURE=Jfamas1
#exec MESHMAP SETTEXTURE MESHMAP=FAMAS NUM=2 TEXTURE=Jfamas2
#exec MESHMAP SETTEXTURE MESHMAP=FAMAS NUM=3 TEXTURE=Jfamas3
#exec MESHMAP SETTEXTURE MESHMAP=FAMAS NUM=4 TEXTURE=Jfamas4
#exec MESHMAP SETTEXTURE MESHMAP=FAMAS NUM=5 TEXTURE=arms_sf


// FAMAS 3rdPerson
#exec MESH IMPORT MESH=wFAMAS ANIVFILE=MODELS\FAMAS\wFAMAS_a.3d DATAFILE=MODELS\FAMAS\wFAMAS_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=wFAMAS  STRENGTH=0.5
#exec MESH ORIGIN MESH=wFAMAS X=50 Y=-50 Z=-20 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wFAMAS1 FILE=TEXTURES\WEAPONS\FAMAS\w_fa1b.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=wFAMAS2 FILE=TEXTURES\WEAPONS\FAMAS\w_fa2b.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wFAMAS MESH=wFAMAS
#exec MESHMAP SCALE MESHMAP=wFAMAS X=0.04 Y=0.04 Z=0.08


#exec MESHMAP SETTEXTURE MESHMAP=wFAMAS NUM=1 TEXTURE=wFAMAS1
#exec MESHMAP SETTEXTURE MESHMAP=wFAMAS NUM=2 TEXTURE=wFAMAS2


// FAMAS Pickup
#exec MESH IMPORT MESH=pFAMAS ANIVFILE=MODELS\FAMAS\wFAMAS_a.3d DATAFILE=MODELS\FAMAS\wFAMAS_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pFAMAS  STRENGTH=0.5
#exec MESH ORIGIN MESH=pFAMAS X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pFAMAS MESH=pFAMAS
#exec MESHMAP SCALE MESHMAP=pFAMAS X=0.045 Y=0.045 Z=0.09

#exec MESHMAP SETTEXTURE MESHMAP=pFAMAS NUM=1 TEXTURE=wFAMAS1
#exec MESHMAP SETTEXTURE MESHMAP=pFAMAS NUM=2 TEXTURE=wFAMAS2



///////////////////////////////////////
// SteyrAug
///////////////////////////////////////


// SteyrAug 1st person model
#exec MESH IMPORT MESH=SteyrAug ANIVFILE=MODELS\SteyrAug\aug_a.3d DATAFILE=MODELS\SteyrAug\aug_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=SteyrAug  STRENGTH=0.5
#exec MESH ORIGIN MESH=SteyrAug X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=SteyrAug SEQ=All				 STARTFRAME=0		NUMFRAMES=56
#exec MESH SEQUENCE MESH=SteyrAug SEQ=RELOAD     STARTFRAME=0		NUMFRAMES=32	
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIRE       STARTFRAME=32	NUMFRAMES=5		RATE 15
#exec MESH SEQUENCE MESH=SteyrAug SEQ=DOWN       STARTFRAME=37	NUMFRAMES=4		RATE 15 
#exec MESH SEQUENCE MESH=SteyrAug SEQ=SELECT     STARTFRAME=41	NUMFRAMES=13	RATE 20	
#exec MESH SEQUENCE MESH=SteyrAug SEQ=IDLE1      STARTFRAME=54	NUMFRAMES=2 
#exec MESH SEQUENCE MESH=SteyrAug SEQ=IDLE       STARTFRAME=54	NUMFRAMES=2
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIX				 STARTFRAME=54	NUMFRAMES=2
 
#exec MESH NOTIFY MESH=SteyrAug SEQ=RELOAD TIME=0.22 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=SteyrAug SEQ=RELOAD TIME=0.50 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=SteyrAug SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=SteyrAug SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire

/*
0-31 reload
32-36 fire
37-40 down
41-53 up
54-55 2frame

#exec MESH SEQUENCE MESH=SteyrAug SEQ=All				 STARTFRAME=0		NUMFRAMES=129
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIRE       STARTFRAME=0		NUMFRAMES=7
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIRE2      STARTFRAME=7		NUMFRAMES=7
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIRE3      STARTFRAME=14	NUMFRAMES=7
#exec MESH SEQUENCE MESH=SteyrAug SEQ=DOWN       STARTFRAME=21	NUMFRAMES=7 
#exec MESH SEQUENCE MESH=SteyrAug SEQ=SELECT     STARTFRAME=28	NUMFRAMES=17
#exec MESH SEQUENCE MESH=SteyrAug SEQ=SCOPE	     STARTFRAME=45	NUMFRAMES=5
#exec MESH SEQUENCE MESH=SteyrAug SEQ=IDLE1      STARTFRAME=50	NUMFRAMES=12 
#exec MESH SEQUENCE MESH=SteyrAug SEQ=IDLE       STARTFRAME=63	NUMFRAMES=2
#exec MESH SEQUENCE MESH=SteyrAug SEQ=FIX				 STARTFRAME=63	NUMFRAMES=2
#exec MESH SEQUENCE MESH=SteyrAug SEQ=RELOAD     STARTFRAME=65	NUMFRAMES=63 
*/

#exec TEXTURE IMPORT NAME=JSteyrAug1 FILE=TEXTURES\WEAPONS\SteyrAug\augbarrel.pcx	GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JSteyrAug2 FILE=TEXTURES\WEAPONS\SteyrAug\augclamps.pcx	GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JSteyrAug3 FILE=TEXTURES\WEAPONS\SteyrAug\augbase.pcx		GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=SteyrAug MESH=SteyrAug
#exec MESHMAP SCALE MESHMAP=SteyrAug X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=SteyrAug NUM=1 TEXTURE=JSteyrAug1
#exec MESHMAP SETTEXTURE MESHMAP=SteyrAug NUM=2 TEXTURE=JSteyrAug2
#exec MESHMAP SETTEXTURE MESHMAP=SteyrAug NUM=3 TEXTURE=JSteyrAug3
#exec MESHMAP SETTEXTURE MESHMAP=SteyrAug NUM=4 TEXTURE=arms_sf

// SteyrAug 3rdPerson
#exec MESH IMPORT MESH=wAug ANIVFILE=MODELS\SteyrAug\waug_a.3d DATAFILE=MODELS\SteyrAug\waug_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wAug  STRENGTH=0.5
#exec MESH ORIGIN MESH=wAug X=0 Y=100 Z=-40 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wJAug1 FILE=TEXTURES\WEAPONS\SteyrAug\augworld1.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=wJAug2 FILE=TEXTURES\WEAPONS\SteyrAug\augworld2.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wAug MESH=wAug
#exec MESHMAP SCALE MESHMAP=wAug X=0.035 Y=0.035 Z=0.07


#exec MESHMAP SETTEXTURE MESHMAP=wAug NUM=1 TEXTURE=wJAug1
#exec MESHMAP SETTEXTURE MESHMAP=wAug NUM=2 TEXTURE=wJAug2


// SteyrAug Pickup
#exec MESH IMPORT MESH=pAug ANIVFILE=MODELS\SteyrAug\waug_a.3d DATAFILE=MODELS\SteyrAug\waug_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pAug  STRENGTH=0.5
#exec MESH ORIGIN MESH=pAug X=200 Y=7 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pAug MESH=pAug
#exec MESHMAP SCALE MESHMAP=pAug X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=pAug NUM=1 TEXTURE=wJAug1
#exec MESHMAP SETTEXTURE MESHMAP=pAug NUM=2 TEXTURE=wJAug2


///////////////////////////////////////
// Ak47
///////////////////////////////////////


// 1st person model
#exec MESH IMPORT MESH=Ak47 ANIVFILE=MODELS\Ak47\Ak47_a.3d DATAFILE=MODELS\Ak47\Ak47_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=Ak47  STRENGTH=0.5
#exec MESH ORIGIN MESH=Ak47 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0


#exec MESH SEQUENCE MESH=Ak47 SEQ=All				STARTFRAME=0		NUMFRAMES=60
#exec MESH SEQUENCE MESH=Ak47 SEQ=Reload		STARTFRAME=0		NUMFRAMES=33
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fire			STARTFRAME=33		NUMFRAMES=6		RATE 15
#exec MESH SEQUENCE MESH=Ak47 SEQ=Down			STARTFRAME=39		NUMFRAMES=5		RATE 15
#exec MESH SEQUENCE MESH=Ak47 SEQ=SELECT    STARTFRAME=44		NUMFRAMES=14	RATE 10
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fix				STARTFRAME=60		NUMFRAMES=2
#exec MESH SEQUENCE MESH=Ak47 SEQ=IDLE      STARTFRAME=60		NUMFRAMES=2
#exec MESH SEQUENCE MESH=Ak47 SEQ=IDLE1     STARTFRAME=60		NUMFRAMES=2

#exec MESH NOTIFY MESH=Ak47 SEQ=RELOAD TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=Ak47 SEQ=RELOAD TIME=0.60 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=Ak47 SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=Ak47 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire

/*
ak47-
1- clip
2- forearm
3- grip
4- main
5- misc
6- stock
7- hands

0-32 reload
33-38 fire
39-43 down
44-57 up
58-59 2frame

#exec MESH SEQUENCE MESH=Ak47 SEQ=All				STARTFRAME=0		NUMFRAMES=167
#exec MESH SEQUENCE MESH=Ak47 SEQ=Reload		STARTFRAME=0		NUMFRAMES=70
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fire			STARTFRAME=70		NUMFRAMES=14
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fix				STARTFRAME=70		NUMFRAMES=2
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fire1			STARTFRAME=84		NUMFRAMES=12
#exec MESH SEQUENCE MESH=Ak47 SEQ=Fire2			STARTFRAME=96		NUMFRAMES=13
#exec MESH SEQUENCE MESH=Ak47 SEQ=Down			STARTFRAME=109	NUMFRAMES=10
#exec MESH SEQUENCE MESH=Ak47 SEQ=IDLE      STARTFRAME=119	NUMFRAMES=1
#exec MESH SEQUENCE MESH=Ak47 SEQ=IDLE1     STARTFRAME=119	NUMFRAMES=12
#exec MESH SEQUENCE MESH=Ak47 SEQ=SELECT    STARTFRAME=131	NUMFRAMES=36
*/

#exec TEXTURE IMPORT NAME=JAk471 FILE=TEXTURES\WEAPONS\Ak47\clipd.pcx			GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JAk472 FILE=TEXTURES\WEAPONS\Ak47\foregripd.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JAk473 FILE=TEXTURES\WEAPONS\Ak47\gripd.pcx			GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JAk474 FILE=TEXTURES\WEAPONS\Ak47\mainj.pcx			GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JAk475 FILE=TEXTURES\WEAPONS\Ak47\miscd.pcx			GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JAk476 FILE=TEXTURES\WEAPONS\Ak47\stockd.pcx		GROUP="Skins"	LODSET=2 


#exec MESHMAP NEW   MESHMAP=Ak47 MESH=Ak47
#exec MESHMAP SCALE MESHMAP=Ak47 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=1 TEXTURE=JAk471
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=2 TEXTURE=JAk472
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=3 TEXTURE=JAk473
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=4 TEXTURE=JAk474
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=5 TEXTURE=JAk475
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=6 TEXTURE=JAk476
#exec MESHMAP SETTEXTURE MESHMAP=Ak47 NUM=7 TEXTURE=arms_sf

// AK47 3rdPerson
#exec MESH IMPORT MESH=wAK47 ANIVFILE=MODELS\ak47\wak47_a.3d DATAFILE=MODELS\ak47\wak47_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wAK47  STRENGTH=0.5
#exec MESH ORIGIN MESH=wAK47 X=0 Y=230 Z=30 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wJak471 FILE=TEXTURES\WEAPONS\ak47\w_ak1d.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=wJak472 FILE=TEXTURES\WEAPONS\ak47\w_ak2d.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wAK47 MESH=wAK47
#exec MESHMAP SCALE MESHMAP=wAK47 X=0.045 Y=0.045 Z=0.09


#exec MESHMAP SETTEXTURE MESHMAP=wAK47 NUM=1 TEXTURE=wJak471
#exec MESHMAP SETTEXTURE MESHMAP=wAK47 NUM=2 TEXTURE=wJak472


// AK47 Pickup
#exec MESH IMPORT MESH=pAK47 ANIVFILE=MODELS\ak47\wak47_a.3d DATAFILE=MODELS\ak47\wak47_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pAK47  STRENGTH=0.5
#exec MESH ORIGIN MESH=pAK47 X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pAK47 MESH=pAK47
#exec MESHMAP SCALE MESHMAP=pAK47 X=0.045 Y=0.045 Z=0.09

#exec MESHMAP SETTEXTURE MESHMAP=pAK47 NUM=1 TEXTURE=wJak471
#exec MESHMAP SETTEXTURE MESHMAP=pAK47 NUM=2 TEXTURE=wJak472



///////////////////////////////////////
// Saiga
///////////////////////////////////////


// 1st person model
#exec MESH IMPORT MESH=Saiga ANIVFILE=MODELS\Saiga\Saiga_a.3d DATAFILE=MODELS\Saiga\Saiga_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=Saiga  STRENGTH=0.5
#exec MESH ORIGIN MESH=Saiga X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0


#exec MESH SEQUENCE MESH=Saiga SEQ=All			STARTFRAME=0		NUMFRAMES=65
#exec MESH SEQUENCE MESH=Saiga SEQ=Fire			STARTFRAME=0		NUMFRAMES=5		RATE 12
#exec MESH SEQUENCE MESH=Saiga SEQ=Down			STARTFRAME=5		NUMFRAMES=6		RATE 15
#exec MESH SEQUENCE MESH=Saiga SEQ=SELECT   STARTFRAME=12		NUMFRAMES=8		RATE 10
#exec MESH SEQUENCE MESH=Saiga SEQ=IDLE1    STARTFRAME=21		NUMFRAMES=11	RATE 10
#exec MESH SEQUENCE MESH=Saiga SEQ=Reload		STARTFRAME=32		NUMFRAMES=30  RATE 15
#exec MESH SEQUENCE MESH=Saiga SEQ=Fix			STARTFRAME=62		NUMFRAMES=2
#exec MESH SEQUENCE MESH=Saiga SEQ=IDLE     STARTFRAME=62		NUMFRAMES=2

#exec MESH NOTIFY MESH=Saiga SEQ=RELOAD TIME=0.26 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=Saiga SEQ=RELOAD TIME=0.55 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=Saiga SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=Saiga SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
/*
	skins-

skin1- siaga1
skin2- siaga2
skin3- hands

anims-

0-4 fire
5-11 down
12-20 up
21-31 idle
32-61 reload
62-63 2frame
*/

#exec TEXTURE IMPORT NAME=JSaiga1 FILE=TEXTURES\WEAPONS\Saiga\saiga1.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JSaiga2 FILE=TEXTURES\WEAPONS\Saiga\saiga2.pcx		GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=Saiga MESH=Saiga
#exec MESHMAP SCALE MESHMAP=Saiga X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=Saiga NUM=1 TEXTURE=JSaiga1
#exec MESHMAP SETTEXTURE MESHMAP=Saiga NUM=2 TEXTURE=JSaiga2
#exec MESHMAP SETTEXTURE MESHMAP=Saiga NUM=3 TEXTURE=arms_sf


// Saiga 3rdPerson
#exec MESH IMPORT MESH=wsaiga ANIVFILE=MODELS\Saiga\Saigaw_a.3d DATAFILE=MODELS\Saiga\Saigaw_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wsaiga  STRENGTH=0.5
#exec MESH ORIGIN MESH=wsaiga X=0 Y=-350 Z=-30 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wsaiga1 FILE=TEXTURES\WEAPONS\Saiga\saigaworld.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wsaiga MESH=wsaiga
#exec MESHMAP SCALE MESHMAP=wsaiga X=0.03 Y=0.03 Z=0.06

#exec MESHMAP SETTEXTURE MESHMAP=wsaiga NUM=1 TEXTURE=wsaiga1


// Saiga Pickup
#exec MESH IMPORT MESH=psaiga ANIVFILE=MODELS\Saiga\Saigaw_a.3d DATAFILE=MODELS\Saiga\Saigaw_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=psaiga  STRENGTH=0.5
#exec MESH ORIGIN MESH=psaiga X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=psaiga MESH=psaiga
#exec MESHMAP SCALE MESHMAP=psaiga X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=psaiga NUM=1 TEXTURE=wsaiga1



///////////////////////////////////////
// HK 33
///////////////////////////////////////


// 1st person model
#exec MESH IMPORT MESH=HK33 ANIVFILE=MODELS\HK33\HK33k_a.3d DATAFILE=MODELS\HK33\HK33k_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=HK33  STRENGTH=0.5
#exec MESH ORIGIN MESH=HK33 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0


#exec MESH SEQUENCE MESH=HK33 SEQ=All				STARTFRAME=0		NUMFRAMES=65
#exec MESH SEQUENCE MESH=HK33 SEQ=Fire			STARTFRAME=0		NUMFRAMES=6		RATE 15
#exec MESH SEQUENCE MESH=HK33 SEQ=Down			STARTFRAME=6		NUMFRAMES=7		RATE 15
#exec MESH SEQUENCE MESH=HK33 SEQ=SELECT    STARTFRAME=13		NUMFRAMES=7		RATE 10
#exec MESH SEQUENCE MESH=HK33 SEQ=IDLE1     STARTFRAME=21		NUMFRAMES=9		RATE 10
#exec MESH SEQUENCE MESH=HK33 SEQ=Reload		STARTFRAME=30		NUMFRAMES=33  RATE 15
#exec MESH SEQUENCE MESH=HK33 SEQ=Fix				STARTFRAME=63		NUMFRAMES=2
#exec MESH SEQUENCE MESH=HK33 SEQ=IDLE      STARTFRAME=63		NUMFRAMES=2

#exec MESH NOTIFY MESH=HK33 SEQ=RELOAD TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=HK33 SEQ=RELOAD TIME=0.55 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=HK33 SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=HK33 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire

/*
0-5 fire
6-12 down
13-20 up
21-29 eyecandy_idle
30-62 reload
63-64 2framer
*/

#exec TEXTURE IMPORT NAME=JHK331 FILE=TEXTURES\WEAPONS\HK33\33BASE.pcx			GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JHK332 FILE=TEXTURES\WEAPONS\HK33\clamp33.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JHK333 FILE=TEXTURES\WEAPONS\HK33\forearm33.pcx	GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=HK33 MESH=HK33
#exec MESHMAP SCALE MESHMAP=HK33 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=HK33 NUM=1 TEXTURE=JHK331
#exec MESHMAP SETTEXTURE MESHMAP=HK33 NUM=2 TEXTURE=JHK332
#exec MESHMAP SETTEXTURE MESHMAP=HK33 NUM=3 TEXTURE=JHK333
#exec MESHMAP SETTEXTURE MESHMAP=HK33 NUM=4 TEXTURE=arms_sf


// HK 33 3rdPerson
#exec MESH IMPORT MESH=whk33 ANIVFILE=MODELS\hk33\hk33world_a.3d DATAFILE=MODELS\hk33\hk33world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=whk33  STRENGTH=0.5
#exec MESH ORIGIN MESH=whk33 X=0 Y=-250 Z=-90 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=whk331 FILE=TEXTURES\WEAPONS\hk33\hk33world.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=whk33 MESH=whk33
#exec MESHMAP SCALE MESHMAP=whk33 X=0.025 Y=0.025 Z=0.05

#exec MESHMAP SETTEXTURE MESHMAP=whk33 NUM=1 TEXTURE=whk331


// HK 33 Pickup
#exec MESH IMPORT MESH=phk33 ANIVFILE=MODELS\hk33\hk33world_a.3d DATAFILE=MODELS\hk33\hk33world_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=phk33  STRENGTH=0.5
#exec MESH ORIGIN MESH=phk33 X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=phk33 MESH=phk33
#exec MESHMAP SCALE MESHMAP=phk33 X=0.03 Y=0.03 Z=0.06

#exec MESHMAP SETTEXTURE MESHMAP=phk33 NUM=1 TEXTURE=whk331



///////////////////////////////////////
// MP5K PDW
///////////////////////////////////////


// 1st person model
#exec MESH IMPORT MESH=mp5kpdw ANIVFILE=MODELS\mp5kpdw\mp5kpdw_a.3d DATAFILE=MODELS\mp5kpdw\mp5kpdw_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=mp5kpdw  STRENGTH=0.5
#exec MESH ORIGIN MESH=mp5kpdw X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=mp5kpdw SEQ=All			STARTFRAME=0		NUMFRAMES=65
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=Fire			STARTFRAME=0		NUMFRAMES=5		RATE 10
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=Down			STARTFRAME=5		NUMFRAMES=6		RATE 10
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=SELECT   STARTFRAME=12		NUMFRAMES=11	RATE 5
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=IDLE     STARTFRAME=23		NUMFRAMES=9		RATE 10
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=Reload		STARTFRAME=30		NUMFRAMES=36  RATE 15
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=Fix			STARTFRAME=66		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5kpdw SEQ=IDLE     STARTFRAME=66		NUMFRAMES=2

#exec MESH NOTIFY MESH=mp5kpdw SEQ=RELOAD TIME=0.26 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=mp5kpdw SEQ=RELOAD TIME=0.50 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=mp5kpdw SEQ=RELOAD TIME=0.82 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mp5kpdw SEQ=Fire		TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=mp5kpdw SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire

/*
skins-

skin1 detail1
skin2 mainbody
skin3 woot1
skin4 hands

animations-

0-4 shoot
5-11 down
12-22 up
23-29 idle
30-65 reload
66-67 2framer
*/

#exec TEXTURE IMPORT NAME=Jmp5kpdw1 FILE=TEXTURES\WEAPONS\mp5kpdw\Detail1.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jmp5kpdw2 FILE=TEXTURES\WEAPONS\mp5kpdw\mainbody1.pcx	GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jmp5kpdw3 FILE=TEXTURES\WEAPONS\mp5kpdw\woot1.pcx			GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=mp5kpdw MESH=mp5kpdw
#exec MESHMAP SCALE MESHMAP=mp5kpdw X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=mp5kpdw NUM=1 TEXTURE=Jmp5kpdw1
#exec MESHMAP SETTEXTURE MESHMAP=mp5kpdw NUM=2 TEXTURE=Jmp5kpdw2
#exec MESHMAP SETTEXTURE MESHMAP=mp5kpdw NUM=3 TEXTURE=Jmp5kpdw3
#exec MESHMAP SETTEXTURE MESHMAP=mp5kpdw NUM=4 TEXTURE=arms_sf


// MP5K PDW 3rdPerson
#exec MESH IMPORT MESH=wmp5kpdw ANIVFILE=MODELS\mp5kpdw\mp5kW_a.3d DATAFILE=MODELS\mp5kpdw\mp5kW_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wmp5kpdw  STRENGTH=0.5
#exec MESH ORIGIN MESH=wmp5kpdw X=0 Y=-100 Z=-100 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wmp5kpdw1 FILE=TEXTURES\WEAPONS\MP5kpdw\mp5kworld.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wmp5kpdw MESH=wmp5kpdw
#exec MESHMAP SCALE MESHMAP=wmp5kpdw X=0.022 Y=0.022 Z=0.044

#exec MESHMAP SETTEXTURE MESHMAP=wmp5kpdw NUM=1 TEXTURE=wmp5kpdw1


// MP5K PDW Pickup
#exec MESH IMPORT MESH=pmp5kpdw ANIVFILE=MODELS\mp5kpdw\mp5kW_a.3d DATAFILE=MODELS\mp5kpdw\mp5kW_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pmp5kpdw  STRENGTH=0.5
#exec MESH ORIGIN MESH=pmp5kpdw X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pmp5kpdw MESH=pmp5kpdw
#exec MESHMAP SCALE MESHMAP=pmp5kpdw X=0.04 Y=0.04 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=pmp5kpdw NUM=1 TEXTURE=wmp5kpdw1



///////////////////////////////////////
// INGRAM MAC 10
///////////////////////////////////////

// INGRAM MAC 10 1st person model
#exec MESH IMPORT MESH=mac10 ANIVFILE=MODELS\MAC10\mac101_a.3d DATAFILE=MODELS\MAC10\mac101_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=mac10  STRENGTH=0.5
#exec MESH ORIGIN MESH=mac10 X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=mac10 SEQ=All           STARTFRAME=0		NUMFRAMES=92
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE          STARTFRAME=0		NUMFRAMES=7	
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE2         STARTFRAME=7		NUMFRAMES=6	
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE3         STARTFRAME=13	NUMFRAMES=6
#exec MESH SEQUENCE MESH=mac10 SEQ=RELOAD        STARTFRAME=19	NUMFRAMES=40
#exec MESH SEQUENCE MESH=mac10 SEQ=DOWN          STARTFRAME=59	NUMFRAMES=16	RATE=20
#exec MESH SEQUENCE MESH=mac10 SEQ=SELECT        STARTFRAME=75	NUMFRAMES=15	RATE=20
#exec MESH SEQUENCE MESH=mac10 SEQ=IDLE          STARTFRAME=90	NUMFRAMES=2	
#exec MESH SEQUENCE MESH=mac10 SEQ=IDLE1         STARTFRAME=90	NUMFRAMES=2	
#exec MESH SEQUENCE MESH=mac10 SEQ=FIX					 STARTFRAME=90	NUMFRAMES=2	

#exec MESH NOTIFY MESH=mac10 SEQ=RELOAD TIME=0.14 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=mac10 SEQ=RELOAD TIME=0.66 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=mac10 SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mac10 SEQ=SELECT TIME=0.53 FUNCTION=Draw1
#exec MESH NOTIFY MESH=mac10 SEQ=SELECT TIME=0.82 FUNCTION=Draw2
#exec MESH NOTIFY MESH=mac10 SEQ=DOWN TIME=0.48 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mac10 SEQ=DOWN TIME=0.96 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mac10 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
/*
fire1 0-6
fire2 7-12
fire3 13-18
reload 19-58
down 59-74
up 75-89
2frameidle 90-91

#exec MESH SEQUENCE MESH=mac10 SEQ=All           STARTFRAME=0 NUMFRAMES=223
#exec MESH SEQUENCE MESH=mac10 SEQ=RELOAD        STARTFRAME=0 NUMFRAMES=94
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE          STARTFRAME=94 NUMFRAMES=9
#exec MESH SEQUENCE MESH=mac10 SEQ=FIX			 STARTFRAME=94 NUMFRAMES=2
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE2         STARTFRAME=103 NUMFRAMES=9
#exec MESH SEQUENCE MESH=mac10 SEQ=FIRE3         STARTFRAME=112 NUMFRAMES=9
#exec MESH SEQUENCE MESH=mac10 SEQ=DOWN          STARTFRAME=131 NUMFRAMES=47
#exec MESH SEQUENCE MESH=mac10 SEQ=SELECT        STARTFRAME=178 NUMFRAMES=45
#exec MESH SEQUENCE MESH=mac10 SEQ=IDLE          STARTFRAME=121 NUMFRAMES=1
#exec MESH SEQUENCE MESH=mac10 SEQ=IDLE1         STARTFRAME=121 NUMFRAMES=10
*/

#exec TEXTURE IMPORT NAME=Jmac101 FILE=TEXTURES\WEAPONS\MAC10\magazine.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jmac102 FILE=TEXTURES\WEAPONS\MAC10\main.pcx		GROUP="Skins"		LODSET=2
#exec TEXTURE IMPORT NAME=Jmac103 FILE=TEXTURES\WEAPONS\MAC10\rail.pcx		GROUP="Skins"		LODSET=2 

#exec MESHMAP NEW   MESHMAP=mac10 MESH=mac10
#exec MESHMAP SCALE MESHMAP=mac10 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=mac10 NUM=1 TEXTURE=Jmac101
#exec MESHMAP SETTEXTURE MESHMAP=mac10 NUM=2 TEXTURE=Jmac102
#exec MESHMAP SETTEXTURE MESHMAP=mac10 NUM=3 TEXTURE=Jmac103
#exec MESHMAP SETTEXTURE MESHMAP=mac10 NUM=4 TEXTURE=arms_sf


// INGRAM MAC 10 3rdPerson
#exec MESH IMPORT MESH=mac10w ANIVFILE=MODELS\MAC10\wmac10_a.3d DATAFILE=MODELS\MAC10\wmac10_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=mac10w  STRENGTH=0.5
#exec MESH ORIGIN MESH=mac10w X=200 Y=0 Z=70 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=mac10w1 FILE=TEXTURES\WEAPONS\MAC10\mac10_world.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=mac10w MESH=mac10w
#exec MESHMAP SCALE MESHMAP=mac10w X=0.0090 Y=0.0090 Z=0.018

#exec MESHMAP SETTEXTURE MESHMAP=mac10w NUM=1 TEXTURE=mac10w1


// INGRAM MAC 10 Pickup
#exec MESH IMPORT MESH=mac10p ANIVFILE=MODELS\MAC10\wmac10_a.3d DATAFILE=MODELS\MAC10\wmac10_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=mac10p  STRENGTH=0.5
#exec MESH ORIGIN MESH=mac10p X=600 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=mac10p MESH=mac10p
#exec MESHMAP SCALE MESHMAP=mac10p X=0.015 Y=0.015 Z=0.03

#exec MESHMAP SETTEXTURE MESHMAP=mac10p NUM=1 TEXTURE=mac10w1



///////////////////////////////////////
// HK MP5 Navy
///////////////////////////////////////
  
// HK MP5 Navy 1st person model
#exec MESH IMPORT MESH=mp5N ANIVFILE=MODELS\MP5-N\mp5_a.3d DATAFILE=MODELS\MP5-N\mp5_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=mp5N  STRENGTH=0.5
#exec MESH ORIGIN MESH=mp5N X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=mp5N	SEQ=All 					STARTFRAME=0 			NUMFRAMES=160
#exec MESH SEQUENCE MESH=mp5N	SEQ=ReloadS		 		STARTFRAME=0 			NUMFRAMES=30	RATE 12
#exec MESH SEQUENCE MESH=mp5N	SEQ=ReloadNS			STARTFRAME=30 		NUMFRAMES=30	RATE 12
#exec MESH SEQUENCE MESH=mp5N	SEQ=SOff					STARTFRAME=60 		NUMFRAMES=15	RATE 12
#exec MESH SEQUENCE MESH=mp5N	SEQ=SOn 					STARTFRAME=75 		NUMFRAMES=15	RATE 12
#exec MESH SEQUENCE MESH=mp5N	SEQ=DownS 				STARTFRAME=90 		NUMFRAMES=7		RATE 20
#exec MESH SEQUENCE MESH=mp5N	SEQ=DownNS	 			STARTFRAME=97 		NUMFRAMES=7		RATE 20
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectFirstS 	STARTFRAME=104 		NUMFRAMES=18	RATE 10
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectFirstNS	STARTFRAME=122 		NUMFRAMES=18	RATE 10
#exec MESH SEQUENCE MESH=mp5N	SEQ=IDLENS				STARTFRAME=140		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=FixNS 				STARTFRAME=140 		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=IDLES					STARTFRAME=142 		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=FixS					STARTFRAME=142 		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=FireS					STARTFRAME=144 		NUMFRAMES=8	RATE 21
#exec MESH SEQUENCE MESH=mp5N	SEQ=FireNS 				STARTFRAME=152 		NUMFRAMES=8	RATE 21

#exec MESH NOTIFY MESH=mp5N SEQ=RELOADS TIME=0.27 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=mp5N SEQ=RELOADS TIME=0.60 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=mp5N SEQ=RELOADS TIME=0.83 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mp5N SEQ=RELOADNS TIME=0.27 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=mp5N SEQ=RELOADNS TIME=0.60 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=mp5N SEQ=RELOADNS TIME=0.83 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=mp5N SEQ=SelectFirstS TIME=0.42 FUNCTION=Draw1
#exec MESH NOTIFY MESH=mp5N SEQ=SelectFirstS TIME=0.80 FUNCTION=Draw2
#exec MESH NOTIFY MESH=mp5N SEQ=SelectFirstNS TIME=0.42 FUNCTION=Draw1
#exec MESH NOTIFY MESH=mp5N SEQ=SelectFirstNS TIME=0.80 FUNCTION=Draw2
#exec MESH NOTIFY MESH=mp5N SEQ=FireS	 TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=mp5N SEQ=FireNS	 TIME=0.10 FUNCTION=AnimFire
/*
0-29 reloadsil
30-59 reloadnosil
60-74 siloff
75-89 silon
90-96 downsil
97-102 downnosil
103-120 drawsil
121-128 drawnosil
139-140 2framenosil
141-142 2framesil
143-150 firesil
151-158 firenosil

#exec MESH SEQUENCE MESH=mp5N	SEQ=All 					STARTFRAME=0 			NUMFRAMES=478
#exec MESH SEQUENCE MESH=mp5N	SEQ=ReloadS		 		STARTFRAME=0 			NUMFRAMES=75
#exec MESH SEQUENCE MESH=mp5N	SEQ=ReloadNS			STARTFRAME=75 		NUMFRAMES=75
#exec MESH SEQUENCE MESH=mp5N	SEQ=FireS					STARTFRAME=151 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=FixS					STARTFRAME=165 		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=Fire2S	 			STARTFRAME=166 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=Fire3S				STARTFRAME=181 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelFireS			STARTFRAME=196 		NUMFRAMES=5
#exec MESH SEQUENCE MESH=mp5N	SEQ=DownS 				STARTFRAME=202 		NUMFRAMES=10
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectLastS		STARTFRAME=212 		NUMFRAMES=10
#exec MESH SEQUENCE MESH=mp5N	SEQ=FireNS 				STARTFRAME=223 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=FixNS 				STARTFRAME=237 		NUMFRAMES=2
#exec MESH SEQUENCE MESH=mp5N	SEQ=Fire2NS 			STARTFRAME=238 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=Fire3NS 			STARTFRAME=253 		NUMFRAMES=14
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelFireNS 		STARTFRAME=268 		NUMFRAMES=5
#exec MESH SEQUENCE MESH=mp5N	SEQ=DownNS	 			STARTFRAME=274 		NUMFRAMES=10
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectLastNS 	STARTFRAME=284 		NUMFRAMES=10
#exec MESH SEQUENCE MESH=mp5N	SEQ=SOff					STARTFRAME=295 		NUMFRAMES=35
#exec MESH SEQUENCE MESH=mp5N	SEQ=SOn 					STARTFRAME=331 		NUMFRAMES=35
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectFirstS 	STARTFRAME=367 		NUMFRAMES=55
#exec MESH SEQUENCE MESH=mp5N	SEQ=SelectFirstNS	STARTFRAME=423 		NUMFRAMES=55
#exec MESH SEQUENCE MESH=mp5N	SEQ=IDLES					STARTFRAME=0 			NUMFRAMES=1
#exec MESH SEQUENCE MESH=mp5N	SEQ=IDLENS				STARTFRAME=76			NUMFRAMES=1
*/
#exec TEXTURE IMPORT NAME=Jmp5N1 FILE=TEXTURES\WEAPONS\MP5-N\forearm.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jmp5N2 FILE=TEXTURES\WEAPONS\MP5-N\magazine.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jmp5N3 FILE=TEXTURES\WEAPONS\MP5-N\main.pcx			GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=mp5N MESH=mp5N
#exec MESHMAP SCALE MESHMAP=mp5N X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=mp5N NUM=1 TEXTURE=Jmp5N1
#exec MESHMAP SETTEXTURE MESHMAP=mp5N NUM=2 TEXTURE=Jmp5N2
#exec MESHMAP SETTEXTURE MESHMAP=mp5N NUM=3 TEXTURE=Jmp5N3
#exec MESHMAP SETTEXTURE MESHMAP=mp5N NUM=4 TEXTURE=arms_sf


// HK MP5 Navy 3rdPerson
#exec MESH IMPORT MESH=wmp5n ANIVFILE=MODELS\MP5-N\mp5world_a.3d DATAFILE=MODELS\MP5-N\mp5world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wmp5n  STRENGTH=0.5
#exec MESH ORIGIN MESH=wmp5n X=0 Y=-300 Z=-40 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wmp5n1 FILE=TEXTURES\WEAPONS\MP5-N\mp5nworld.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wmp5n MESH=wmp5n
#exec MESHMAP SCALE MESHMAP=wmp5n X=0.025 Y=0.025 Z=0.050

#exec MESHMAP SETTEXTURE MESHMAP=wmp5n NUM=1 TEXTURE=wmp5n1


// HK MP5 Navy Pickup
#exec MESH IMPORT MESH=pmp5n ANIVFILE=MODELS\MP5-N\mp5world_a.3d DATAFILE=MODELS\MP5-N\mp5world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pmp5n  STRENGTH=0.5
#exec MESH ORIGIN MESH=pmp5n X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pmp5n MESH=pmp5n
#exec MESHMAP SCALE MESHMAP=pmp5n X=0.025 Y=0.025 Z=0.050

#exec MESHMAP SETTEXTURE MESHMAP=pmp5n NUM=1 TEXTURE=wmp5n1



///////////////////////////////////////
// HK SR9
///////////////////////////////////////

#exec MESH IMPORT			MESH=hksr9	ANIVFILE=MODELS\hksr9\sr9_a.3d DATAFILE=MODELS\hksr9\sr9_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=hksr9  STRENGTH=0.5
#exec MESH ORIGIN			MESH=hksr9	X=0 Y=0 Z=0 YAW=192

#exec MESH SEQUENCE MESH=hksr9 SEQ=All				STARTFRAME=0		NUMFRAMES=61
#exec MESH SEQUENCE MESH=hksr9 SEQ=Reload     STARTFRAME=0		NUMFRAMES=32	RATE 8 // 0.3
#exec MESH SEQUENCE MESH=hksr9 SEQ=Down       STARTFRAME=32		NUMFRAMES=11
#exec MESH SEQUENCE MESH=hksr9 SEQ=Select     STARTFRAME=43		NUMFRAMES=7		RATE 6 // 0.2
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fire       STARTFRAME=50		NUMFRAMES=9		RATE 20	// 0.6
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fix        STARTFRAME=59		NUMFRAMES=2
#exec MESH SEQUENCE MESH=hksr9 SEQ=Idle       STARTFRAME=59		NUMFRAMES=2
#exec MESH SEQUENCE MESH=hksr9 SEQ=Idle1      STARTFRAME=59		NUMFRAMES=2

#exec MESH NOTIFY MESH=hksr9 SEQ=RELOAD TIME=0.18 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=hksr9 SEQ=RELOAD TIME=0.58 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=hksr9 SEQ=RELOAD TIME=0.85 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=hksr9 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
/*
0-31 reload
32-42 down
43-49 up
50-58 fire
59-60 2frame

#exec MESH SEQUENCE MESH=hksr9 SEQ=All				STARTFRAME=0		NUMFRAMES=224
#exec MESH SEQUENCE MESH=hksr9 SEQ=Reload     STARTFRAME=0		NUMFRAMES=110
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fire       STARTFRAME=110	NUMFRAMES=14
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fix        STARTFRAME=110	NUMFRAMES=2
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fire2      STARTFRAME=124	NUMFRAMES=16
#exec MESH SEQUENCE MESH=hksr9 SEQ=Fire2      STARTFRAME=140	NUMFRAMES=16
#exec MESH SEQUENCE MESH=hksr9 SEQ=Down       STARTFRAME=156	NUMFRAMES=11
#exec MESH SEQUENCE MESH=hksr9 SEQ=Select     STARTFRAME=167	NUMFRAMES=37
#exec MESH SEQUENCE MESH=hksr9 SEQ=Idle       STARTFRAME=204	NUMFRAMES=1
#exec MESH SEQUENCE MESH=hksr9 SEQ=Idle1      STARTFRAME=204	NUMFRAMES=20
*/

#exec MESHMAP NEW   MESHMAP=hksr9 MESH=hksr9
#exec MESHMAP SCALE MESHMAP=hksr9 X=0.05 Y=0.05 Z=0.1

#exec TEXTURE IMPORT NAME=Jhksr9_01 FILE=Textures\Weapons\hksr9\sr9_clip.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jhksr9_02 FILE=Textures\Weapons\hksr9\sr9_main.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=Jhksr9_03 FILE=Textures\Weapons\hksr9\sr9_main2.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jhksr9_04 FILE=Textures\Weapons\hksr9\sr9_main3.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jhksr9_05 FILE=Textures\Weapons\hksr9\sr9_misc.pcx	 GROUP="Skins"	LODSET=2 

#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=1 TEXTURE=Jhksr9_01
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=2 TEXTURE=Jhksr9_02
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=3 TEXTURE=Jhksr9_03
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=4 TEXTURE=Jhksr9_04
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=5 TEXTURE=Jhksr9_05
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=6 TEXTURE=arms_sf
/*

sr9-
1- main
2- clip
3- main2
4- main3
5- misc
6- hands
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=2 TEXTURE=Jhksr9_01
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=1 TEXTURE=Jhksr9_02
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=4 TEXTURE=Jhksr9_03
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=5 TEXTURE=Jhksr9_04
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=3 TEXTURE=Jhksr9_05
#exec MESHMAP SETTEXTURE MESHMAP=hksr9 NUM=6 TEXTURE=arms_sf
*/
// HK SR9 3rdPerson
#exec MESH IMPORT MESH=whksr9 ANIVFILE=MODELS\hksr9\wsr_a.3d DATAFILE=MODELS\hksr9\wsr_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=whksr9  STRENGTH=0.5
#exec MESH ORIGIN MESH=whksr9 X=0 Y=-200 Z=25 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=Jwhksr91 FILE=TEXTURES\WEAPONS\hksr9\w_sr1.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=Jwhksr92 FILE=TEXTURES\WEAPONS\hksr9\w_sr2.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=whksr9 MESH=whksr9
#exec MESHMAP SCALE MESHMAP=whksr9 X=0.045 Y=0.045 Z=0.09

#exec MESHMAP SETTEXTURE MESHMAP=whksr9 NUM=1 TEXTURE=Jwhksr91
#exec MESHMAP SETTEXTURE MESHMAP=whksr9 NUM=2 TEXTURE=Jwhksr92


// HK SR9 Pickup
#exec MESH IMPORT MESH=phksr9 ANIVFILE=MODELS\hksr9\wsr_a.3d DATAFILE=MODELS\hksr9\wsr_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=phksr9  STRENGTH=0.5
#exec MESH ORIGIN MESH=phksr9 X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=phksr9 MESH=phksr9
#exec MESHMAP SCALE MESHMAP=phksr9 X=0.05 Y=0.05 Z=0.10

#exec MESHMAP SETTEXTURE MESHMAP=phksr9 NUM=1 TEXTURE=Jwhksr91
#exec MESHMAP SETTEXTURE MESHMAP=phksr9 NUM=2 TEXTURE=Jwhksr92



///////////////////////////////////////
// HK PSG1
///////////////////////////////////////

#exec MESH IMPORT			MESH=PSG1	ANIVFILE=MODELS\PSG1\PSG1_a.3d DATAFILE=MODELS\PSG1\PSG1_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=PSG1  STRENGTH=0.5
#exec MESH ORIGIN			MESH=PSG1	X=50 Y=-25 Z=25 YAW=192 PITCH=-10

#exec MESH SEQUENCE MESH=PSG1 SEQ=All				STARTFRAME=0		NUMFRAMES=75
#exec MESH SEQUENCE MESH=PSG1 SEQ=Reload		STARTFRAME=0		NUMFRAMES=38
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fire			STARTFRAME=38		NUMFRAMES=6
#exec MESH SEQUENCE MESH=PSG1 SEQ=Select    STARTFRAME=46   NUMFRAMES=17	RATE=10
#exec MESH SEQUENCE MESH=PSG1 SEQ=Down      STARTFRAME=63		NUMFRAMES=10
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fix				STARTFRAME=73		NUMFRAMES=2
#exec MESH SEQUENCE MESH=PSG1 SEQ=Idle      STARTFRAME=73		NUMFRAMES=2
#exec MESH SEQUENCE MESH=PSG1 SEQ=Idle1     STARTFRAME=73		NUMFRAMES=2

#exec MESH NOTIFY MESH=PSG1 SEQ=RELOAD TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=PSG1 SEQ=RELOAD TIME=0.60 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=PSG1 SEQ=RELOAD TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=PSG1 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
/*
reload 0-37
fire1 38-45
up 46-62
down 63-72
2frameidle 73-74

#exec MESH SEQUENCE MESH=PSG1 SEQ=All				STARTFRAME=0		NUMFRAMES=192
#exec MESH SEQUENCE MESH=PSG1 SEQ=Reload		STARTFRAME=0		NUMFRAMES=79
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fire			STARTFRAME=79		NUMFRAMES=15
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fix				STARTFRAME=79		NUMFRAMES=2
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fire2     STARTFRAME=94		NUMFRAMES=15
#exec MESH SEQUENCE MESH=PSG1 SEQ=Fire3     STARTFRAME=109  NUMFRAMES=15
#exec MESH SEQUENCE MESH=PSG1 SEQ=Idle      STARTFRAME=124	NUMFRAMES=1
#exec MESH SEQUENCE MESH=PSG1 SEQ=Idle1     STARTFRAME=124	NUMFRAMES=15
#exec MESH SEQUENCE MESH=PSG1 SEQ=Down      STARTFRAME=139  NUMFRAMES=12
#exec MESH SEQUENCE MESH=PSG1 SEQ=Select    STARTFRAME=151  NUMFRAMES=32
#exec MESH SEQUENCE MESH=PSG1 SEQ=scope     STARTFRAME=183	NUMFRAMES=9
*/

#exec MESHMAP NEW   MESHMAP=PSG1 MESH=PSG1
#exec MESHMAP SCALE MESHMAP=PSG1 X=0.05 Y=0.05 Z=0.1

#exec TEXTURE IMPORT NAME=JPSG1_01 FILE=Textures\Weapons\PSG1\buttstock.pcx	GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JPSG1_02 FILE=Textures\Weapons\PSG1\forearm.pcx		GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JPSG1_03 FILE=Textures\Weapons\PSG1\main.pcx				GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JPSG1_04 FILE=Textures\Weapons\PSG1\others.pcx			GROUP="Skins"	LODSET=2 

#exec MESHMAP SETTEXTURE MESHMAP=PSG1 NUM=1 TEXTURE=JPSG1_01
#exec MESHMAP SETTEXTURE MESHMAP=PSG1 NUM=2 TEXTURE=JPSG1_02
#exec MESHMAP SETTEXTURE MESHMAP=PSG1 NUM=3 TEXTURE=JPSG1_03
#exec MESHMAP SETTEXTURE MESHMAP=PSG1 NUM=4 TEXTURE=JPSG1_04
#exec MESHMAP SETTEXTURE MESHMAP=PSG1 NUM=5 TEXTURE=arms_sf


// PSG1 3rdPerson
#exec MESH IMPORT MESH=wPSG1 ANIVFILE=MODELS\PSG1\wpsg_a.3d DATAFILE=MODELS\PSG1\wpsg_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wPSG1  STRENGTH=0.5
#exec MESH ORIGIN MESH=wPSG1 X=0 Y=150 Z=-85 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wPSG11 FILE=TEXTURES\WEAPONS\PSG1\w_psg1.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=wPSG12 FILE=TEXTURES\WEAPONS\PSG1\w_psg2.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wPSG1 MESH=wPSG1
#exec MESHMAP SCALE MESHMAP=wPSG1 X=0.055 Y=0.055 Z=0.11


#exec MESHMAP SETTEXTURE MESHMAP=wPSG1 NUM=1 TEXTURE=wPSG11
#exec MESHMAP SETTEXTURE MESHMAP=wPSG1 NUM=2 TEXTURE=wPSG12


// PSG1 Pickup
#exec MESH IMPORT MESH=pPSG1 ANIVFILE=MODELS\PSG1\wpsg_a.3d DATAFILE=MODELS\PSG1\wpsg_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=pPSG1  STRENGTH=0.5
#exec MESH ORIGIN MESH=pPSG1 X=160 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pPSG1 MESH=pPSG1
#exec MESHMAP SCALE MESHMAP=pPSG1 X=0.06 Y=0.06 Z=0.12

#exec MESHMAP SETTEXTURE MESHMAP=pPSG1 NUM=1 TEXTURE=wPSG11
#exec MESHMAP SETTEXTURE MESHMAP=pPSG1 NUM=2 TEXTURE=wPSG12



///////////////////////////////////////
// p85
///////////////////////////////////////

#exec MESH IMPORT			MESH=P85	ANIVFILE=MODELS\P85\Ph85_a.3d DATAFILE=MODELS\P85\Ph85_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS	MESH=P85  STRENGTH=0.5
#exec MESH ORIGIN			MESH=P85	X=50 Y=-25 Z=25 YAW=192 PITCH=-5


#exec MESH SEQUENCE MESH=P85 SEQ=All			STARTFRAME=0		NUMFRAMES=273
#exec MESH SEQUENCE MESH=P85 SEQ=Reload		STARTFRAME=0		NUMFRAMES=35	RATE 8  // 0.3
#exec MESH SEQUENCE MESH=P85 SEQ=Fire			STARTFRAME=35		NUMFRAMES=19	RATE 10 // 0.36
#exec MESH SEQUENCE MESH=P85 SEQ=Down     STARTFRAME=54		NUMFRAMES=9		RATE 15 // 0.5
#exec MESH SEQUENCE MESH=P85 SEQ=Select   STARTFRAME=63		NUMFRAMES=12	RATE 15 // 0.5
#exec MESH SEQUENCE MESH=P85 SEQ=Idle     STARTFRAME=75		NUMFRAMES=2
#exec MESH SEQUENCE MESH=P85 SEQ=Idle1    STARTFRAME=75		NUMFRAMES=2
#exec MESH SEQUENCE MESH=P85 SEQ=Fix			STARTFRAME=75		NUMFRAMES=2

#exec MESH NOTIFY MESH=P85 SEQ=Fire TIME=0.20 FUNCTION=ZoomOut
#exec MESH NOTIFY MESH=P85 SEQ=Fire TIME=0.55 FUNCTION=PlayP85Reload
#exec MESH NOTIFY MESH=P85 SEQ=RELOAD TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=P85 SEQ=RELOAD TIME=0.70 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=P85 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire

/*
0-34 reload
35-53 shoot
54-62 away
63-74 draw
75-76 2frame
 

#exec MESH SEQUENCE MESH=P85 SEQ=All			STARTFRAME=0		NUMFRAMES=273
#exec MESH SEQUENCE MESH=P85 SEQ=Reload		STARTFRAME=157	NUMFRAMES=115
#exec MESH SEQUENCE MESH=P85 SEQ=Fire			STARTFRAME=87		NUMFRAMES=52
#exec MESH SEQUENCE MESH=P85 SEQ=Fix			STARTFRAME=87		NUMFRAMES=2
#exec MESH SEQUENCE MESH=P85 SEQ=Fire2    STARTFRAME=139	NUMFRAMES=18
#exec MESH SEQUENCE MESH=P85 SEQ=Idle     STARTFRAME=45		NUMFRAMES=1
#exec MESH SEQUENCE MESH=P85 SEQ=Idle1    STARTFRAME=45		NUMFRAMES=31
#exec MESH SEQUENCE MESH=P85 SEQ=Down     STARTFRAME=0		NUMFRAMES=19
#exec MESH SEQUENCE MESH=P85 SEQ=Select   STARTFRAME=19		NUMFRAMES=26
#exec MESH SEQUENCE MESH=P85 SEQ=scope    STARTFRAME=76		NUMFRAMES=21
*/
#exec MESHMAP NEW   MESHMAP=P85 MESH=P85
#exec MESHMAP SCALE MESHMAP=P85 X=0.05 Y=0.05 Z=0.1

#exec TEXTURE IMPORT NAME=JP85_01 FILE=Textures\Weapons\P85\1t.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JP85_02 FILE=Textures\Weapons\P85\2t.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JP85_03 FILE=Textures\Weapons\P85\3t.pcx GROUP="Skins"	LODSET=2
#exec TEXTURE IMPORT NAME=JP85_04 FILE=Textures\Weapons\P85\4t.pcx GROUP="Skins"	LODSET=2 
#exec TEXTURE IMPORT NAME=JP85_05 FILE=Textures\Weapons\P85\5t.pcx GROUP="Skins"	LODSET=2


#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=1 TEXTURE=JP85_01
#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=2 TEXTURE=JP85_02
#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=3 TEXTURE=JP85_03
#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=4 TEXTURE=JP85_04
#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=5 TEXTURE=JP85_05
#exec MESHMAP SETTEXTURE MESHMAP=P85 NUM=6 TEXTURE=arms_sf


// p85 3rdPerson
#exec MESH IMPORT MESH=wp85 ANIVFILE=MODELS\p85\p85world_a.3d DATAFILE=MODELS\p85\p85world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wp85  STRENGTH=0.5
#exec MESH ORIGIN MESH=wp85 X=0 Y=-200 Z=-50 YAW=-64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wJp851 FILE=TEXTURES\WEAPONS\p85\p85side.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wp85 MESH=wp85
#exec MESHMAP SCALE MESHMAP=wp85 X=0.04 Y=0.04 Z=0.08


#exec MESHMAP SETTEXTURE MESHMAP=wp85 NUM=1 TEXTURE=wJp851


// p85 Pickup
#exec MESH IMPORT MESH=pp85 ANIVFILE=MODELS\p85\p85world_a.3d DATAFILE=MODELS\p85\p85world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pp85  STRENGTH=0.5
#exec MESH ORIGIN MESH=pp85 X=200 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pp85 MESH=pp85
#exec MESHMAP SCALE MESHMAP=pp85 X=0.05 Y=0.05 Z=0.10

#exec MESHMAP SETTEXTURE MESHMAP=pp85 NUM=1 TEXTURE=wJp851


///////////////////////////////////////
// OICW
///////////////////////////////////////

// OICW 1st person model
#exec MESH IMPORT MESH=OICW ANIVFILE=MODELS\OICW\oicw_a.3d DATAFILE=MODELS\OICW\oicw_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=OICW  STRENGTH=0.5
#exec MESH ORIGIN MESH=OICW X=0 Y=0 Z=0 YAW=180 PITCH=0 ROLL=-5
// #exec MESH ORIGIN MESH=OICW X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=OICW SEQ=All				 STARTFRAME=0		NUMFRAMES=98
#exec MESH SEQUENCE MESH=OICW SEQ=RELOAD1    STARTFRAME=0		NUMFRAMES=30	RATE 11
#exec MESH SEQUENCE MESH=OICW SEQ=RELOAD2    STARTFRAME=31	NUMFRAMES=28	RATE 12
#exec MESH SEQUENCE MESH=OICW SEQ=FIRE       STARTFRAME=59	NUMFRAMES=8		RATE 15
#exec MESH SEQUENCE MESH=OICW SEQ=FIRE2      STARTFRAME=67	NUMFRAMES=10	RATE 18
#exec MESH SEQUENCE MESH=OICW SEQ=DOWN       STARTFRAME=77	NUMFRAMES=7		RATE 15 
#exec MESH SEQUENCE MESH=OICW SEQ=SELECT     STARTFRAME=84	NUMFRAMES=12  RATE 16
#exec MESH SEQUENCE MESH=OICW SEQ=IDLE       STARTFRAME=96	NUMFRAMES=2
#exec MESH SEQUENCE MESH=OICW SEQ=IDLE1      STARTFRAME=96	NUMFRAMES=2
#exec MESH SEQUENCE MESH=OICW SEQ=FIX		     STARTFRAME=96	NUMFRAMES=2

#exec MESH NOTIFY MESH=OICW SEQ=RELOAD1 TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=OICW SEQ=RELOAD1 TIME=0.60 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=OICW SEQ=RELOAD1 TIME=0.80 FUNCTION=ClipLever
#exec MESH NOTIFY MESH=OICW SEQ=RELOAD2 TIME=0.30 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=OICW SEQ=RELOAD2 TIME=0.70 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=OICW SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=OICW SEQ=Fire2	 TIME=0.10 FUNCTION=AnimFire
/*
0-30 reload556
31-58 reload20
59-66 shoot20
67-76 shoot556
77-83 down
84-95 up
96-97 2frame

#exec MESH SEQUENCE MESH=OICW SEQ=All				 STARTFRAME=0		NUMFRAMES=264
#exec MESH SEQUENCE MESH=OICW SEQ=RELOAD1    STARTFRAME=112		NUMFRAMES=81
#exec MESH SEQUENCE MESH=OICW SEQ=RELOAD2    STARTFRAME=193		NUMFRAMES=71
#exec MESH SEQUENCE MESH=OICW SEQ=FIRE       STARTFRAME=37		NUMFRAMES=14
#exec MESH SEQUENCE MESH=OICW SEQ=FIX		     STARTFRAME=66		NUMFRAMES=2
#exec MESH SEQUENCE MESH=OICW SEQ=FIRE2      STARTFRAME=51		NUMFRAMES=16
#exec MESH SEQUENCE MESH=OICW SEQ=DOWN       STARTFRAME=0	  NUMFRAMES=15 
#exec MESH SEQUENCE MESH=OICW SEQ=IDLE       STARTFRAME=67	NUMFRAMES=1
#exec MESH SEQUENCE MESH=OICW SEQ=IDLE1      STARTFRAME=67	NUMFRAMES=45
#exec MESH SEQUENCE MESH=OICW SEQ=SELECT     STARTFRAME=15	NUMFRAMES=22 
*/

#exec TEXTURE IMPORT NAME=JOICW1 FILE=TEXTURES\WEAPONS\OICW\oicw_body.pcx	GROUP="Skins"		LODSET=2
#exec TEXTURE IMPORT NAME=JOICW2 FILE=TEXTURES\WEAPONS\OICW\oicw_scope.pcx GROUP="Skins"		LODSET=2 

#exec MESHMAP NEW   MESHMAP=OICW MESH=OICW
#exec MESHMAP SCALE MESHMAP=OICW X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=OICW NUM=1 TEXTURE=JOICW1
#exec MESHMAP SETTEXTURE MESHMAP=OICW NUM=2 TEXTURE=JOICW2
#exec MESHMAP SETTEXTURE MESHMAP=OICW NUM=3 TEXTURE=arms_sf

// OICW 3rdPerson
#exec MESH IMPORT MESH=wOICW ANIVFILE=MODELS\OICW\oicw3rd_a.3d DATAFILE=MODELS\OICW\oicw3rd_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wOICW  STRENGTH=0.5
#exec MESH ORIGIN MESH=wOICW X=-100 Y=60 Z=-80 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wOICW1 FILE=TEXTURES\WEAPONS\OICW\oicw_3rd.pcx GROUP="Skins"	LODSET=2 

#exec MESHMAP NEW   MESHMAP=wOICW MESH=wOICW
#exec MESHMAP SCALE MESHMAP=wOICW X=0.04 Y=0.035 Z=0.08


#exec MESHMAP SETTEXTURE MESHMAP=wOICW NUM=1 TEXTURE=wOICW1

// OICW Pickup
#exec MESH IMPORT MESH=pOICW ANIVFILE=MODELS\OICW\oicw3rd_a.3d DATAFILE=MODELS\OICW\oicw3rd_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pOICW  STRENGTH=0.5
#exec MESH ORIGIN MESH=pOICW X=0 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pOICW MESH=pOICW
#exec MESHMAP SCALE MESHMAP=pOICW  X=0.04 Y=0.035 Z=0.08

#exec MESHMAP SETTEXTURE MESHMAP=pOICW NUM=1 TEXTURE=wOICW1




///////////////////////////////////////
// M4m203
///////////////////////////////////////

// M4m203 1st person model
#exec MESH IMPORT MESH=M4m203 ANIVFILE=MODELS\M4m203\M4m203_a.3d DATAFILE=MODELS\M4m203\M4m203_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=M4m203  STRENGTH=0.5
#exec MESH ORIGIN MESH=M4m203 X=0 Y=0 Z=0 YAW=189 PITCH=0 ROLL=0 
//X=0 Y=0 Z=0 YAW=180 PITCH=0 ROLL=-5
// #exec MESH ORIGIN MESH=OICW X=0 Y=0 Z=0 YAW=192 PITCH=0 ROLL=0

#exec MESH SEQUENCE MESH=M4m203 SEQ=All					STARTFRAME=0		NUMFRAMES=108
#exec MESH SEQUENCE MESH=M4m203 SEQ=FIRE				STARTFRAME=0		NUMFRAMES=5
#exec MESH SEQUENCE MESH=M4m203 SEQ=DOWN				STARTFRAME=5		NUMFRAMES=10	RATE 15 
#exec MESH SEQUENCE MESH=M4m203 SEQ=SELECT			STARTFRAME=15		NUMFRAMES=9		RATE 16
#exec MESH SEQUENCE MESH=M4m203 SEQ=IDLE1				STARTFRAME=24		NUMFRAMES=12
#exec MESH SEQUENCE MESH=M4m203 SEQ=FIREGREN		STARTFRAME=36		NUMFRAMES=11	RATE 18
#exec MESH SEQUENCE MESH=M4m203 SEQ=RELOADGREN	STARTFRAME=47		NUMFRAMES=24	RATE 11
#exec MESH SEQUENCE MESH=M4m203 SEQ=RELOAD			STARTFRAME=71		NUMFRAMES=36	RATE 12
#exec MESH SEQUENCE MESH=M4m203 SEQ=IDLE				STARTFRAME=23		NUMFRAMES=2
#exec MESH SEQUENCE MESH=M4m203 SEQ=FIX					STARTFRAME=23		NUMFRAMES=2

#exec MESH NOTIFY MESH=M4m203 SEQ=RELOAD TIME=0.30 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=M4m203 SEQ=RELOAD TIME=0.70 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=M4m203 SEQ=RELOADGREN TIME=0.20 FUNCTION=ClipIn
#exec MESH NOTIFY MESH=M4m203 SEQ=RELOADGREN TIME=0.80 FUNCTION=ClipOut
#exec MESH NOTIFY MESH=M4m203 SEQ=Fire	 TIME=0.10 FUNCTION=AnimFire
#exec MESH NOTIFY MESH=M4m203 SEQ=FireGren	 TIME=0.10 FUNCTION=AnimFire

/*
anims
0-4 fire
5-14 down
15-23 up
24-35 idle (SLOOOOOOOOOW)
36-46 firegren (SLOOOOOOOW)
47-70 reloadgren
71-106 reload
107-108 2frame

skins
skin1 m4basebo
skin2 m4grip
skin3 m4mag
skin4 hands
*/

#exec TEXTURE IMPORT NAME=JM4m2031 FILE=TEXTURES\WEAPONS\M4m203\m4basebo.pcx	GROUP="Skins"		LODSET=2
#exec TEXTURE IMPORT NAME=JM4m2032 FILE=TEXTURES\WEAPONS\M4m203\m4grip.pcx GROUP="Skins"		LODSET=2 
#exec TEXTURE IMPORT NAME=JM4m2033 FILE=TEXTURES\WEAPONS\M4m203\m4mag.pcx GROUP="Skins"		LODSET=2 

#exec MESHMAP NEW   MESHMAP=M4m203 MESH=M4m203
#exec MESHMAP SCALE MESHMAP=M4m203 X=0.05 Y=0.05 Z=0.1

#exec MESHMAP SETTEXTURE MESHMAP=M4m203 NUM=1 TEXTURE=JM4m2031
#exec MESHMAP SETTEXTURE MESHMAP=M4m203 NUM=2 TEXTURE=JM4m2032
#exec MESHMAP SETTEXTURE MESHMAP=M4m203 NUM=3 TEXTURE=JM4m2033
#exec MESHMAP SETTEXTURE MESHMAP=M4m203 NUM=4 TEXTURE=arms_sf


// M4m203 3rdPerson
#exec MESH IMPORT MESH=wM4m203 ANIVFILE=MODELS\M4m203\m4world_a.3d DATAFILE=MODELS\M4m203\m4world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=wM4m203  STRENGTH=0.5
#exec MESH ORIGIN MESH=wM4m203  X=0 Y=400 Z=-90 YAW=64 PITCH=0 ROLL=0

#exec TEXTURE IMPORT NAME=wM4m2031 FILE=TEXTURES\WEAPONS\M4m203\m4m203world.pcx GROUP="Skins"	LODSET=2

#exec MESHMAP NEW   MESHMAP=wM4m203 MESH=wM4m203
#exec MESHMAP SCALE MESHMAP=wM4m203 X=0.025 Y=0.025 Z=0.05

#exec MESHMAP SETTEXTURE MESHMAP=wM4m203 NUM=1 TEXTURE=wM4m2031

// M4m203 Pickup
#exec MESH IMPORT MESH=pM4m203 ANIVFILE=MODELS\M4m203\m4world_a.3d DATAFILE=MODELS\M4m203\m4world_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=pM4m203  STRENGTH=0.5
#exec MESH ORIGIN MESH=pM4m203 X=400 Y=0 Z=0 YAW=-64 PITCH=64 ROLL=0

#exec MESHMAP NEW   MESHMAP=pM4m203 MESH=pM4m203
#exec MESHMAP SCALE MESHMAP=pM4m203  X=0.03 Y=0.03 Z=0.06

#exec MESHMAP SETTEXTURE MESHMAP=pM4m203 NUM=1 TEXTURE=wM4m2031


///////////////////////////////////////
// EvidenceMoney
///////////////////////////////////////

#exec MESH IMPORT MESH=mny_bundle ANIVFILE=MODELS\pickup\s_e_money_bundle_a.3d DATAFILE=MODELS\pickup\s_e_money_bundle_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=mny_bundle  STRENGTH=0.5
#exec MESH ORIGIN MESH=mny_bundle X=0 Y=0 Z=0

#exec MESHMAP NEW   MESHMAP=mny_bundle MESH=mny_bundle
#exec MESHMAP SCALE MESHMAP=mny_bundle X=0.05 Y=0.05 Z=0.10

#exec TEXTURE IMPORT NAME=Jmny_bundle_01 FILE=Textures\Skins\Pickup\money_bundle_01b.PCX GROUP="Skins"	LODSET=2 

#exec MESHMAP SETTEXTURE MESHMAP=mny_bundle NUM=1 TEXTURE=Jmny_bundle_01


///////////////////////////////////////
// EvidenceMarijuana
///////////////////////////////////////

#exec MESH IMPORT MESH=ev_weed ANIVFILE=MODELS\EV_Marijuana\weed_a.3d DATAFILE=MODELS\EV_Marijuana\weed_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=ev_weed  STRENGTH=0.5
#exec MESH ORIGIN MESH=ev_weed X=0 Y=0 Z=150

#exec MESHMAP NEW   MESHMAP=ev_weed MESH=mny_bundle
#exec MESHMAP SCALE MESHMAP=ev_weed X=0.03 Y=0.03 Z=0.06

#exec TEXTURE IMPORT NAME=Jweed		FILE=Textures\Skins\Pickup\weed.pcx  GROUP="Skins"	LODSET=2 
//#exec TEXTURE IMPORT NAME=Jweed2	FILE=Textures\Skins\Pickup\weed2.bmp GROUP="Skins"	LODSET=2 

#exec MESHMAP SETTEXTURE MESHMAP=ev_weed NUM=1 TEXTURE=Jweed
//#exec MESHMAP SETTEXTURE MESHMAP=ev_weed NUM=2 TEXTURE=Jweed2


///////////////////////////////////////
// Money pickup
///////////////////////////////////////

#exec MESH IMPORT MESH=mny1 ANIVFILE=MODELS\pickup\s_e_money1_a.3d DATAFILE=MODELS\pickup\s_e_money1_d.3d X=0 Y=0 Z=0 
//#exec MESH LODPARAMS MESH=mny1  STRENGTH=0.5
#exec MESH ORIGIN MESH=mny1 X=0 Y=0 Z=5

#exec MESHMAP NEW   MESHMAP=mny1 MESH=mny1
#exec MESHMAP SCALE MESHMAP=mny1 X=0.03 Y=0.03 Z=0.06

//#exec TEXTURE IMPORT NAME=Jmny1_01 FILE=Textures\Skins\Pickup\money1_01.PCX GROUP="Skins"	LODSET=2 

#exec MESHMAP SETTEXTURE MESHMAP=mny1 NUM=1 TEXTURE=Jmny_bundle_01



///////////////////////////////////////
// Special Items - Cocaine
///////////////////////////////////////

#exec MESH IMPORT MESH=SI_Cocaine ANIVFILE=MODELS\SI_Cocaine\cocain_a.3d DATAFILE=MODELS\SI_Cocaine\cocain_d.3d X=0 Y=0 Z=0
//#exec MESH LODPARAMS MESH=SI_Cocaine  STRENGTH=0.5
#exec MESH ORIGIN MESH=SI_Cocaine X=0 Y=0 Z=0

#exec MESHMAP NEW   MESHMAP=SI_Cocaine MESH=SI_Cocaine
#exec MESHMAP SCALE MESHMAP=SI_Cocaine X=0.02 Y=0.02 Z=0.04

#exec TEXTURE IMPORT NAME=Jcocaine_01 FILE=Textures\Skins\Pickup\cocaine.pcx GROUP="Skins"

#exec MESHMAP SETTEXTURE MESHMAP=SI_Cocaine NUM=1 TEXTURE=Jcocaine_01

defaultproperties
{
}
